target = "compliance/framework/algorithm-suites.txt#2.10.3"

# 2.10.3.  Encryption Algorithm Mode
#
# The AEAD operation mode used with the encryption algorithm.
# 
# The length of the input IV MUST equal the IV length specified by the
# algorithm suite.  The length of the authentication tag MUST equal the
# authentication tag length specified by the algorithm suite.

[[spec]]
level = "MUST"
quote = '''
The length of the input IV MUST equal the IV length specified by the
algorithm suite.
'''

[[spec]]
level = "MUST"
quote = '''
The length of the authentication tag MUST equal the
authentication tag length specified by the algorithm suite.
'''

