target = "compliance/framework/algorithm-suites.txt#2.10.2"

# 2.10.2.  Encryption Algorithm
#
# The block cipher encryption algorithm.
# 
# The length of the input encryption key MUST equal the encryption key
# length (Section 2.10.4) specified by the algorithm suite.

[[spec]]
level = "MUST"
quote = '''
The length of the input encryption key MUST equal the encryption key
length (Section 2.10.4) specified by the algorithm suite.
'''

