target = "compliance/framework/algorithm-suites.txt#2.10.15.1"

# 2.10.15.1.  Supported Algorithm Suite Data
#
# *  Algorithm Suite 05 78 MUST store the commit key in the suite data
# 
# *  Algorithm Suite 04 78 MUST store the commit key in the suite data

[[spec]]
level = "MUST"
quote = '''
*  Algorithm Suite 05 78 MUST store the commit key in the suite data
'''

[[spec]]
level = "MUST"
quote = '''
*  Algorithm Suite 04 78 MUST store the commit key in the suite data
'''

