target = "compliance/framework/algorithm-suites.txt#2.10.11"

# 2.10.11.  Commit Key Derivation Algorithm
#
# This key derivation algorithm defines what key derivation function
# (KDF) to use for commitment key generation.  The specified KDF
# algorithm MUST be used to generate the commit key (Section 2.10.10).

[[spec]]
level = "MUST"
quote = '''
The specified KDF
algorithm MUST be used to generate the commit key (Section 2.10.10).
'''

