target = "compliance/framework/algorithm-suites.txt#2.10"

# 2.10.  Structure
#
# The fields described below are REQUIRED to be specified by algorithm
# suites, unless otherwise specified.

[[spec]]
level = "MUST"
quote = '''
The fields described below are REQUIRED to be specified by algorithm
suites, unless otherwise specified.
'''

