target = "compliance/framework/algorithm-suites.txt#2.10.7"

# 2.10.7.  Encryption Key Derivation Algorithm
#
# This key derivation algorithm defines what key derivation function
# (KDF) to use for encryption key generation.  The specified KDF
# algorithm MUST be used to generate the encryption algorithm
# encryption key input.

[[spec]]
level = "MUST"
quote = '''
The specified KDF
algorithm MUST be used to generate the encryption algorithm
encryption key input.
'''

