target = "compliance/framework/algorithm-suites.txt#2.4.3"

# 2.4.3.  GCM
#
# Specification: NIST Special Publication 800-38D
# (https://nvlpubs.nist.gov/nistpubs/Legacy/SP/
# nistspecialpublication800-38d.pdf)
# 
# Galois/Counter Mode is a mode of operation for block ciphers that
# provides authenticated encryption with additional data (AEAD).
# 
# If specified to use GCM, the AWS Encryption SDK MUST use GCM with the
# following specifics:
# 
# *  The internal block cipher is the encryption algorithm specified by
#    the algorithm suite.

[[spec]]
level = "MUST"
quote = '''
If specified to use GCM, the AWS Encryption SDK MUST use GCM with the
following specifics:
'''

