target = "compliance/framework/algorithm-suites.txt#2.5"

# 2.5.  Supported Algorithm Suites
#
# The following table includes the algorithm suites supported by the
# AWS Encryption SDK.  The value "00 00" is reserved and MUST NOT be
# used as an Algorithm Suite ID in the future.
# 
#  +==========================+================+=====================+
#  | Algorithm Suite ID (hex) | Message Format | Algorithm Suite     |
#  |                          | Version        | Data Length (bytes) |
#  +==========================+================+=====================+
#  | 05 78                    | 2.0            | 32                  |
#  +--------------------------+----------------+---------------------+
#  | 04 78                    | 2.0            | 32                  |
#  +--------------------------+----------------+---------------------+
#  | 03 78                    | 1.0            | N/A                 |
#  +--------------------------+----------------+---------------------+
#  | 03 46                    | 1.0            | N/A                 |
#  +--------------------------+----------------+---------------------+
#  | 02 14                    | 1.0            | N/A                 |
#  +--------------------------+----------------+---------------------+
#  | 01 78                    | 1.0            | N/A                 |
#  +--------------------------+----------------+---------------------+
#  | 01 46                    | 1.0            | N/A                 |
#  +--------------------------+----------------+---------------------+
#  | 01 14                    | 1.0            | N/A                 |
#  +--------------------------+----------------+---------------------+
#  | 00 78                    | 1.0            | N/A                 |
#  +--------------------------+----------------+---------------------+
#  | 00 46                    | 1.0            | N/A                 |
#  +--------------------------+----------------+---------------------+
#  | 00 14                    | 1.0            | N/A                 |
#  +--------------------------+----------------+---------------------+
# 
#                                Table 1

[[spec]]
level = "MUST"
quote = '''
The value "00 00" is reserved and MUST NOT be
used as an Algorithm Suite ID in the future.
'''

