target = "compliance/framework/structures.txt#2.3.3.2.2"

# 2.3.3.2.2.  Encrypted Data Keys
#
# A list of the encrypted data keys (Section 2.3.1) that correspond to
# the plaintext data key.
# 
# The Section 2.3.1.2.3 of each encrypted data key in this list MUST be
# an opaque form of the plaintext data key from this set of encryption
# materials.
# 
# If the plaintext data key is not included in this set of encryption
# materials, this list MUST be empty.

[[spec]]
level = "MUST"
quote = '''
The Section 2.3.1.2.3 of each encrypted data key in this list MUST be
an opaque form of the plaintext data key from this set of encryption
materials.
'''

[[spec]]
level = "MUST"
quote = '''
If the plaintext data key is not included in this set of encryption
materials, this list MUST be empty.
'''

