target = "compliance/framework/structures.txt#2.3.3.2.3"

# 2.3.3.2.3.  Encryption Context
#
# The encryption context (Section 2.3.2) associated with this
# encryption (../client-apis/encrypt.md).
# 
# If an encryption material (Section 2.3.3) contains a signing key
# (Section 2.3.3.2.5), the encryption context (Section 2.3.2) SHOULD
# include the reserved key "aws-crypto-public-key".  The mapped value
# from the reserved key "aws-crypto-public-key" SHOULD be the signature
# verification key corresponding to the signing key (Section 2.3.3.2.5)
# stored on the encryption material (Section 2.3.3).  If an encryption
# material (Section 2.3.3) does not contains a signing key
# (Section 2.3.3.2.5), the encryption context (Section 2.3.2) SHOULD
# NOT include the reserved key "aws-crypto-public-key".

[[spec]]
level = "SHOULD"
quote = '''
If an encryption material (Section 2.3.3) contains a signing key
(Section 2.3.3.2.5), the encryption context (Section 2.3.2) SHOULD
include the reserved key "aws-crypto-public-key".
'''

[[spec]]
level = "SHOULD"
quote = '''
The mapped value
from the reserved key "aws-crypto-public-key" SHOULD be the signature
verification key corresponding to the signing key (Section 2.3.3.2.5)
stored on the encryption material (Section 2.3.3).
'''

[[spec]]
level = "SHOULD"
quote = '''
If an encryption
material (Section 2.3.3) does not contains a signing key
(Section 2.3.3.2.5), the encryption context (Section 2.3.2) SHOULD
NOT include the reserved key "aws-crypto-public-key".
'''

