target = "compliance/framework/structures.txt#2.3.3.2.4"

# 2.3.3.2.4.  Plaintext Data Key
#
# A data key to be used as input for encryption (../client-apis/
# encrypt.md).
# 
# The plaintext data key MUST:
# 
# *  Fit the specification for the key derivation algorithm (algorithm-
#    suites.md#key-derivation-algorithm) included in this decryption
#    material's algorithm suite (Section 2.3.3.2.1).
# 
# *  Consist of cryptographically secure (pseudo-)random bits.
# 
# *  Be kept secret.
# 
# The plaintext data key SHOULD be stored as immutable data.
# 
# The plaintext data key SHOULD offer an interface to zero the
# plaintext data key.

[[spec]]
level = "MUST"
quote = '''
The plaintext data key MUST:
'''

[[spec]]
level = "SHOULD"
quote = '''
The plaintext data key SHOULD be stored as immutable data.
'''

[[spec]]
level = "SHOULD"
quote = '''
The plaintext data key SHOULD offer an interface to zero the
plaintext data key.
'''

