target = "compliance/framework/structures.txt#2.3"

# 2.3.  Overview
#
# This document includes the specifications for common structures
# referenced throughout the AWS Encryption SDK specification.  These
# structures define a group of related fields that MUST hold certain
# properties.  Wherever these structures are referenced in this
# specification, implementations MUST ensure that all properties of a
# structure's fields are upheld.
# 
# Note that this specification does not specify how these structures
# should be represented or passed throughout the AWS Encryption SDK
# framework.  While these structures will usually be represented as
# objects, lower level languages MAY represent these fields in a less
# strictly defined way as long as all field properties are still
# upheld.
# 
# Structures defined in this document:
# 
# *  Encrypted Data Key (Section 2.3.1)
# 
# *  Encryption Context (Section 2.3.2)
# 
# *  Encryption Materials (Section 2.3.3)
# 
# *  Decryption Materials (Section 2.3.4)

[[spec]]
level = "MUST"
quote = '''
These
structures define a group of related fields that MUST hold certain
properties.
'''

[[spec]]
level = "MUST"
quote = '''
Wherever these structures are referenced in this
specification, implementations MUST ensure that all properties of a
structure's fields are upheld.
'''

[[spec]]
level = "MAY"
quote = '''
While these structures will usually be represented as
objects, lower level languages MAY represent these fields in a less
strictly defined way as long as all field properties are still
upheld.
'''

