target = "compliance/framework/structures.txt#2.3.1.2"

# 2.3.1.2.  Structure
#
# An encrypted data key is comprised of the following fields:
# 
# *  Key Provider ID (Section 2.3.1.2.1)
# 
# *  Key Provider Information (Section 2.3.1.2.2)
# 
# *  Section 2.3.1.2.3
# 
# Note: "Encrypted" is a misnomer here, as the process by which a key
# provider may obtain the plaintext data key from the ciphertext and
# vice versa does not have to be an encryption and decryption cipher.
# This specification uses the terms "encrypt" and "decrypt" for
# simplicity, but the actual process by which a key provider obtains
# the plaintext data key from the ciphertext and vice versa MAY be any
# reversible operation, though we expect that most will use encryption.

[[spec]]
level = "MAY"
quote = '''
This specification uses the terms "encrypt" and "decrypt" for
simplicity, but the actual process by which a key provider obtains
the plaintext data key from the ciphertext and vice versa MAY be any
reversible operation, though we expect that most will use encryption.
'''

