target = "compliance/client-apis/streaming.txt#2.2"

# 2.2.  Overview
#
# The AWS Encryption SDK MAY provide APIs that enable streamed
# encryption (encrypt.md) and decryption (decrypt.md).  Streaming is a
# framework for making bytes available to be processed by an operation
# sequentially and over time, and for outputting the result of that
# processing sequentially and over time.
# 
# If an implementation requires holding the entire input in memory in
# order to perform the operation, that implementation SHOULD NOT
# provide an API that allows the caller to stream the operation.  APIs
# that support streaming of the encrypt or decrypt operation SHOULD
# allow customers to be able to process arbitrarily large inputs with a
# finite amount of working memory.

[[spec]]
level = "MAY"
quote = '''
The AWS Encryption SDK MAY provide APIs that enable streamed
encryption (encrypt.md) and decryption (decrypt.md).
'''

[[spec]]
level = "SHOULD"
quote = '''
If an implementation requires holding the entire input in memory in
order to perform the operation, that implementation SHOULD NOT
provide an API that allows the caller to stream the operation.
'''

[[spec]]
level = "SHOULD"
quote = '''
APIs
that support streaming of the encrypt or decrypt operation SHOULD
allow customers to be able to process arbitrarily large inputs with a
finite amount of working memory.
'''

