target = "compliance/client-apis/streaming.txt#2.3.3"

# 2.3.3.  Release
#
# An operation releases bytes when the operation intends those bytes to
# be considered output.
# 
# For example, in a framework where a customer is sending input bytes
# to an operation and that operation must write the output bytes to
# some sink, bytes are considered released once the operation writes
# those bytes into the sink.
# 
# For a framework where a customer is requesting output bytes from an
# operation and that operation must read from some source in order to
# produce bytes, bytes are considered released once those bytes are
# available to be read by the customer.
# 
# If bytes are processed by an operation, that does not imply that the
# operation is allowed to release any result of that processing.  The
# decrypt and encrypt operations specify when output bytes MUST NOT be
# released and when they SHOULD be released.

[[spec]]
level = "MUST"
quote = '''
The
decrypt and encrypt operations specify when output bytes MUST NOT be
released and when they SHOULD be released.
'''

