target = "compliance/client-apis/streaming.txt#2.5"

# 2.5.  Outputs
#
# In order to support streaming, the operation MUST produce some output
# within a streaming framework.
# 
# This means that:
# 
# *  There MUST be a mechanism for output bytes to be released.
# 
# *  There MUST be a mechanism to indicate that the entire output has
#    been released.
# 
# These mechanisms are used to allow the operation to produce output
# bytes in parts, over time.
# 
# The bytes that represent the entire output to the operation are the
# bytes that were released up until an end was indicated.
# 
# Operations MUST NOT indicate completion or success until an end to
# the output has been indicated.

[[spec]]
level = "MUST"
quote = '''
In order to support streaming, the operation MUST produce some output
within a streaming framework.
'''

[[spec]]
level = "MUST"
quote = '''
*  There MUST be a mechanism for output bytes to be released.
'''

[[spec]]
level = "MUST"
quote = '''
*  There MUST be a mechanism to indicate that the entire output has
been released.
'''

[[spec]]
level = "MUST"
quote = '''
Operations MUST NOT indicate completion or success until an end to
the output has been indicated.
'''

