target = "compliance/client-apis/streaming.txt#2.6"

# 2.6.  Behavior
#
# By using the mechanisms for Section 2.4 and Section 2.5, some actor
# expresses intent through a streaming interface for bytes to be made
# consumable to the operation and for bytes to be released by the
# operation.
# 
# The behavior of the operation specifies how the operation processes
# consumable bytes, and specifies when processed bytes MUST NOT and
# SHOULD be released.

[[spec]]
level = "MUST"
quote = '''
The behavior of the operation specifies how the operation processes
consumable bytes, and specifies when processed bytes MUST NOT and
SHOULD be released.
'''

