target = "compliance/framework/local-cryptographic-materials-cache.txt#2.5"

# 2.5.  Initialization
#
# On initialization of the local CMC, the caller MUST provide the
# following:
# 
# *  Entry Capacity (Section 2.5.1)
# 
# The local CMC MUST also define the following:
# 
# *  Entry Pruning Tail Size (Section 2.5.2)

[[spec]]
level = "MUST"
quote = '''
On initialization of the local CMC, the caller MUST provide the
following:
'''

[[spec]]
level = "MUST"
quote = '''
The local CMC MUST also define the following:
'''

