target = "compliance/framework/local-cryptographic-materials-cache.txt#2.5.1"

# 2.5.1.  Entry Capacity
#
# The _entry capacity_ is the maximum size of the local CMC in terms of
# cache entries.  The local CMC MUST NOT store more entries than this
# value, except temporarily while performing a Put Cache Entry
# operation.  The local CMC MUST accept entry capacity values between
# zero and an implementation-defined maximum, inclusive.

[[spec]]
level = "MUST"
quote = '''
The local CMC MUST NOT store more entries than this
value, except temporarily while performing a Put Cache Entry
operation.
'''

[[spec]]
level = "MUST"
quote = '''
The local CMC MUST accept entry capacity values between
zero and an implementation-defined maximum, inclusive.
'''

