target = "compliance/framework/local-cryptographic-materials-cache.txt#2.5.2"

# 2.5.2.  Entry Pruning Tail Size
#
# The _entry pruning tail size_ is the number of least recently used
# entries that the local CMC MUST check during Section 2.7 for TTL-
# expired entries to evict.

[[spec]]
level = "MUST"
quote = '''
The _entry pruning tail size_ is the number of least recently used
entries that the local CMC MUST check during Section 2.7 for TTL-
expired entries to evict.
'''

