target = "compliance/framework/local-cryptographic-materials-cache.txt#2.6.2"

# 2.6.2.  Get Cache Entry
#
# When performing a Get Cache Entry operation, the local CMC MUST prune
# TTL-expired cache entries (Section 2.7).  The local CMC MUST NOT
# return any TTL-expired entry.

[[spec]]
level = "MUST"
quote = '''
When performing a Get Cache Entry operation, the local CMC MUST prune
TTL-expired cache entries (Section 2.7).
'''

[[spec]]
level = "MUST"
quote = '''
The local CMC MUST NOT
return any TTL-expired entry.
'''

