target = "compliance/framework/local-cryptographic-materials-cache.txt#2.6.1"

# 2.6.1.  Put Cache Entry
#
# When calling the Put Cache Entry operation, the caller MUST provide a
# time delta value, which the local CMC uses to derive the cache
# entry's time-to-live (TTL) value.  The local CMC MUST NOT return any
# TTL-expired entry.
# 
# When performing a Put Cache Entry operation, the local CMC MUST prune
# TTL-expired cache entries (Section 2.7).
# 
# While performing a Put Cache Entry operation, the local CMC MAY store
# more entries than the entry capacity.  However, before returning the
# inserted cache entry, the local CMC MUST evict least-recently used
# entries until the number of stored entries does not exceed the entry
# capacity.

[[spec]]
level = "MUST"
quote = '''
When calling the Put Cache Entry operation, the caller MUST provide a
time delta value, which the local CMC uses to derive the cache
entry's time-to-live (TTL) value.
'''

[[spec]]
level = "MUST"
quote = '''
The local CMC MUST NOT return any
TTL-expired entry.
'''

[[spec]]
level = "MUST"
quote = '''
When performing a Put Cache Entry operation, the local CMC MUST prune
TTL-expired cache entries (Section 2.7).
'''

[[spec]]
level = "MAY"
quote = '''
While performing a Put Cache Entry operation, the local CMC MAY store
more entries than the entry capacity.
'''

[[spec]]
level = "MUST"
quote = '''
However, before returning the
inserted cache entry, the local CMC MUST evict least-recently used
entries until the number of stored entries does not exceed the entry
capacity.
'''

