target = "compliance/framework/aws-kms/aws-kms-mrk-aware-multi-keyrings.txt#2.5"

# 2.5.  Discovery Multi-Keyring
#
# The caller MUST provide:
# 
# *  A set of Region strings
# 
# *  An optional discovery filter that is an AWS partition and a set of
#    AWS accounts
# 
# *  An optional method that can take a region string and return an AWS
#    KMS client e.g. a regional client supplier
# 
# *  An optional list of AWS KMS grant tokens
# 
# If an empty set of Region is provided this function MUST fail.  If
# any element of the set of regions is null or an empty string this
# function MUST fail.  If a regional client supplier is not passed,
# then a default MUST be created that takes a region string and
# generates a default AWS SDK client for the given region.
# 
# A set of AWS KMS clients MUST be created by calling regional client
# supplier for each region in the input set of regions.
# 
# Then a set of AWS KMS MRK Aware Symmetric Region Discovery Keyring
# (aws-kms-mrk-aware-symmetric-region-discovery-keyring.md) MUST be
# created for each AWS KMS client by initializing each keyring with
# 
# *  The AWS KMS client
# 
# *  The input discovery filter
# 
# *  The input AWS KMS grant tokens
# 
# Then a Multi-Keyring (../multi-keyring.md#inputs) MUST be initialize
# by using this set of discovery keyrings as the child keyrings
# (../multi-keyring.md#child-keyrings).  This Multi-Keyring MUST be
# this functions output.

[[spec]]
level = "MUST"
quote = '''
The caller MUST provide:
'''

[[spec]]
level = "MUST"
quote = '''
If an empty set of Region is provided this function MUST fail.
'''

[[spec]]
level = "MUST"
quote = '''
If
any element of the set of regions is null or an empty string this
function MUST fail.
'''

[[spec]]
level = "MUST"
quote = '''
If a regional client supplier is not passed,
then a default MUST be created that takes a region string and
generates a default AWS SDK client for the given region.
'''

[[spec]]
level = "MUST"
quote = '''
A set of AWS KMS clients MUST be created by calling regional client
supplier for each region in the input set of regions.
'''

[[spec]]
level = "MUST"
quote = '''
Then a set of AWS KMS MRK Aware Symmetric Region Discovery Keyring
(aws-kms-mrk-aware-symmetric-region-discovery-keyring.md) MUST be
created for each AWS KMS client by initializing each keyring with
'''

[[spec]]
level = "MUST"
quote = '''
Then a Multi-Keyring (../multi-keyring.md#inputs) MUST be initialize
by using this set of discovery keyrings as the child keyrings
(../multi-keyring.md#child-keyrings).
'''

[[spec]]
level = "MUST"
quote = '''
This Multi-Keyring MUST be
this functions output.
'''

