target = "compliance/framework/aws-kms/aws-kms-mrk-aware-multi-keyrings.txt#2.6"

# 2.6.  Strict Multi-Keyring
#
# The caller MUST provide:
# 
# *  An optional AWS KMS key identifiers to use as the generator.
# 
# *  An optional set of AWS KMS key identifiers to us as child
#    keyrings.
# 
# *  An optional method that can take a region string and return an AWS
#    KMS client e.g. a regional client supplier
# 
# *  An optional list of AWS KMS grant tokens
# 
# If any of the AWS KMS key identifiers is null or an empty string this
# function MUST fail.  At least one non-null or non-empty string AWS
# KMS key identifiers exists in the input this function MUST fail.  All
# AWS KMS identifiers are passed to Assert AWS KMS MRK are unique (aws-
# kms-mrk-are-unique.md#Implementation) and the function MUST return
# success otherwise this MUST fail.  If a regional client supplier is
# not passed, then a default MUST be created that takes a region string
# and generates a default AWS SDK client for the given region.
# 
# If there is a generator input then the generator keyring MUST be a
# AWS KMS MRK Aware Symmetric Keyring (aws-kms-mrk-aware-symmetric-
# keyring.md) initialized with
# 
# *  The generator input.
# 
# *  The AWS KMS client that MUST be created by the regional client
#    supplier when called with the region part of the generator ARN or
#    a signal for the AWS SDK to select the default region.
# 
# *  The input list of AWS KMS grant tokens
# 
# If there is a set of child identifiers then a set of AWS KMS MRK
# Aware Symmetric Keyring (aws-kms-mrk-aware-symmetric-keyring.md) MUST
# be created for each AWS KMS key identifier by initialized each
# keyring with
# 
# *  AWS KMS key identifier.
# 
# *  The AWS KMS client that MUST be created by the regional client
#    supplier when called with the region part of the AWS KMS key
#    identifier or a signal for the AWS SDK to select the default
#    region.
# 
# *  The input list of AWS KMS grant tokens
# 
# NOTE: The AWS Encryption SDK SHOULD NOT attempt to evaluate its own
# default region.
# 
# Then a Multi-Keyring (../multi-keyring.md#inputs) MUST be initialize
# by using this generator keyring as the generator keyring (../multi-
# keyring.md#generator-keyring) and this set of child keyrings as the
# child keyrings (../multi-keyring.md#child-keyrings).  This Multi-
# Keyring MUST be this functions output.

[[spec]]
level = "MUST"
quote = '''
The caller MUST provide:
'''

[[spec]]
level = "MUST"
quote = '''
If any of the AWS KMS key identifiers is null or an empty string this
function MUST fail.
'''

[[spec]]
level = "MUST"
quote = '''
At least one non-null or non-empty string AWS
KMS key identifiers exists in the input this function MUST fail.
'''

[[spec]]
level = "MUST"
quote = '''
All
AWS KMS identifiers are passed to Assert AWS KMS MRK are unique (aws-
kms-mrk-are-unique.md#Implementation) and the function MUST return
success otherwise this MUST fail.
'''

[[spec]]
level = "MUST"
quote = '''
All
AWS KMS identifiers are passed to Assert AWS KMS MRK are unique (aws-
kms-mrk-are-unique.md#Implementation) and the function MUST return
success otherwise this MUST fail.
'''

[[spec]]
level = "MUST"
quote = '''
If a regional client supplier is
not passed, then a default MUST be created that takes a region string
and generates a default AWS SDK client for the given region.
'''

[[spec]]
level = "MUST"
quote = '''
If there is a generator input then the generator keyring MUST be a
AWS KMS MRK Aware Symmetric Keyring (aws-kms-mrk-aware-symmetric-
keyring.md) initialized with
'''

[[spec]]
level = "MUST"
quote = '''
*  The AWS KMS client that MUST be created by the regional client
supplier when called with the region part of the generator ARN or
a signal for the AWS SDK to select the default region.
'''

[[spec]]
level = "MUST"
quote = '''
If there is a set of child identifiers then a set of AWS KMS MRK
Aware Symmetric Keyring (aws-kms-mrk-aware-symmetric-keyring.md) MUST
be created for each AWS KMS key identifier by initialized each
keyring with
'''

[[spec]]
level = "MUST"
quote = '''
*  The AWS KMS client that MUST be created by the regional client
supplier when called with the region part of the AWS KMS key
identifier or a signal for the AWS SDK to select the default
region.
'''

[[spec]]
level = "SHOULD"
quote = '''
NOTE: The AWS Encryption SDK SHOULD NOT attempt to evaluate its own
default region.
'''

[[spec]]
level = "MUST"
quote = '''
Then a Multi-Keyring (../multi-keyring.md#inputs) MUST be initialize
by using this generator keyring as the generator keyring (../multi-
keyring.md#generator-keyring) and this set of child keyrings as the
child keyrings (../multi-keyring.md#child-keyrings).
'''

[[spec]]
level = "MUST"
quote = '''
This Multi-
Keyring MUST be this functions output.
'''

