target = "compliance/framework/aws-kms/aws-kms-mrk-aware-symmetric-region-discovery-keyring.txt#2.6"

# 2.6.  Initialization
#
# On initialization the caller MUST provide:
# 
# *  An AWS KMS client
# 
# *  An optional discovery filter that is an AWS partition and a set of
#    AWS accounts
# 
# *  An optional list of AWS KMS grant tokens
# 
# The keyring MUST know what Region the AWS KMS client is in.  It
# SHOULD obtain this information directly from the client as opposed to
# having an additional parameter.  However if it can not, then it MUST
# NOT create the client itself.  It SHOULD have a Region parameter and
# SHOULD try to identify mismatched configurations. i.e. The client is
# in Region A and the Region parameter is B.

[[spec]]
level = "MUST"
quote = '''
On initialization the caller MUST provide:
'''

[[spec]]
level = "MUST"
quote = '''
The keyring MUST know what Region the AWS KMS client is in.
'''

[[spec]]
level = "SHOULD"
quote = '''
It
SHOULD obtain this information directly from the client as opposed to
having an additional parameter.
'''

[[spec]]
level = "MUST"
quote = '''
However if it can not, then it MUST
NOT create the client itself.
'''

[[spec]]
level = "SHOULD"
quote = '''
It SHOULD have a Region parameter and
SHOULD try to identify mismatched configurations.
'''

[[spec]]
level = "SHOULD"
quote = '''
It SHOULD have a Region parameter and
SHOULD try to identify mismatched configurations.
'''

