target = "compliance/framework/aws-kms/aws-kms-mrk-aware-symmetric-region-discovery-keyring.txt#2.7"

# 2.7.  OnEncrypt
#
# This function MUST fail.

[[spec]]
level = "MUST"
quote = '''
This function MUST fail.
'''

