target = "compliance/data-format/message-footer.txt#2.3"

# 2.3.  Overview
#
# The footer is a component of the When an message
# (message.md).algorithm suite (../framework/algorithm-suites.md)
# includes a signature algorithm (../framework/algorithm-
# suites.md#signature-algorithm), the message (message.md) MUST contain
# a footer.

[[spec]]
level = "MUST"
quote = '''
./framework/algorithm-
suites.md#signature-algorithm), the message (message.md) MUST contain
a footer.
'''

