target = "compliance/framework/aws-kms/aws-kms-mrk-match-for-decrypt.txt#2.5"

# 2.5.  Implementation
#
# The caller MUST provide:
# 
# *  2 AWS KMS key identifiers
# 
# If both identifiers are identical, this function MUST return "true".
# Otherwise if either input is not identified as a multi-Region key
# (aws-kms-key-arn.md#identifying-an-aws-kms-multi-region-key), then
# this function MUST return "false".  Otherwise if both inputs are
# identified as a multi-Region keys (aws-kms-key-arn.md#identifying-an-
# aws-kms-multi-region-key), this function MUST return the result of
# comparing the "partition", "service", "accountId", "resourceType",
# and "resource" parts of both ARN inputs.  NOTE: The "region" part is
# intentionally omitted.

[[spec]]
level = "MUST"
quote = '''
The caller MUST provide:
'''

[[spec]]
level = "MUST"
quote = '''
If both identifiers are identical, this function MUST return "true".
'''

[[spec]]
level = "MUST"
quote = '''
Otherwise if either input is not identified as a multi-Region key
(aws-kms-key-arn.md#identifying-an-aws-kms-multi-region-key), then
this function MUST return "false".
'''

[[spec]]
level = "MUST"
quote = '''
Otherwise if both inputs are
identified as a multi-Region keys (aws-kms-key-arn.md#identifying-an-
aws-kms-multi-region-key), this function MUST return the result of
comparing the "partition", "service", "accountId", "resourceType",
and "resource" parts of both ARN inputs.
'''

