target = "compliance/data-format/message-header.txt#2.5.1.11"

# 2.5.1.11.  Content Type
#
# The content type of the message body (message-body.md).  The value
# (hex) of this field MUST be a value that exists in the following
# table:

[[spec]]
level = "MUST"
quote = '''
The value
(hex) of this field MUST be a value that exists in the following
table:
'''

