target = "compliance/data-format/message-header.txt#2.5.2.1"

# 2.5.2.1.  Reserved
#
# A reserved sequence of 4 bytes that MUST have the value (hex) of "00
# 00 00 00".

[[spec]]
level = "MUST"
quote = '''
A reserved sequence of 4 bytes that MUST have the value (hex) of "00
00 00 00".
'''

