target = "compliance/data-format/message-header.txt#2.5.2"

# 2.5.2.  Algorithm Suite Data
#
# A variable length byte sequence interpreted according to the
# algorithm suite.  The length of the suite data field MUST be equal to
# the Algorithm Suite Data Length (../framework/algorithm-
# suites.md#algorithm-suite-data-length) value of the algorithm suite
# (../framework/algorithm-suites.md) specified by the Algorithm Suite
# ID (Section 2.5.1.5) field.

[[spec]]
level = "MUST"
quote = '''
The length of the suite data field MUST be equal to
the Algorithm Suite Data Length (../framework/algorithm-
suites.md#algorithm-suite-data-length) value of the algorithm suite
(../framework/algorithm-suites.md) specified by the Algorithm Suite
ID (Section 2.5.1.5) field.
'''

