target = "compliance/data-format/message-header.txt#2.5.2.2"

# 2.5.2.2.  IV Length
#
# The length of the initialization vector (IV).  This value MUST be
# equal to the IV length (../framework/algorithm-suites.md#iv-length)
# value of the algorithm suite (../framework/algorithm-suites.md)
# specified by the Algorithm Suite ID (Section 2.5.1.5) field.

[[spec]]
level = "MUST"
quote = '''
This value MUST be
equal to the IV length (../framework/algorithm-suites.md#iv-length)
value of the algorithm suite (../framework/algorithm-suites.md)
specified by the Algorithm Suite ID (Section 2.5.1.5) field.
'''

