target = "compliance/data-format/message-header.txt#2.5.1.3"

# 2.5.1.3.  Version
#
# The version of the message format.  The version (hex) of this field
# MUST be a value that exists in the following table:

[[spec]]
level = "MUST"
quote = '''
The version (hex) of this field
MUST be a value that exists in the following table:
'''

