target = "compliance/data-format/message-header.txt#2.5.1.5"

# 2.5.1.5.  Algorithm Suite ID
#
# The identifier for the algorithm suite used when generating the
# message.  The value (hex) of this field MUST be a value that exists
# in the Supported Algorithm Suites (../framework/algorithm-
# suites.md#supported-algorithm-suites) table.

[[spec]]
level = "MUST"
quote = '''
The value (hex) of this field MUST be a value that exists
in the Supported Algorithm Suites (../framework/algorithm-
suites.md#supported-algorithm-suites) table.
'''

