target = "compliance/data-format/message-header.txt#2.5.1.7.2.1"

# 2.5.1.7.2.1.  Key Value Pair Count
#
# The number of key-value pairs within the Key Value Pair Entries
# (Section 2.5.1.7.2.2) field.  The value of this field MUST be greater
# than 0.

[[spec]]
level = "MUST"
quote = '''
The value of this field MUST be greater
than 0.
'''

