target = "compliance/data-format/message-header.txt#2.5.2.3"

# 2.5.2.3.  Frame Length
#
# The length of the encrypted content (message-body.md#encrypted-
# content) within each regular frame (message-body.md#regular-frame) of
# framed content.  When the content type (Section 2.5.1.11) is non-
# framed, the value of this field MUST be 0.

[[spec]]
level = "MUST"
quote = '''
When the content type (Section 2.5.1.11) is non-
framed, the value of this field MUST be 0.
'''

