target = "compliance/data-format/message-header.txt#2.5.1.2"

# 2.5.1.2.  Header Body Version 2.0
#
# The following table describes the fields that form the Version 2.0
# header body.  The bytes are appended in the order shown.
# 
# +===========+=====================+================================+
# | Field     | Length (bytes)      | Interpreted as                 |
# +===========+=====================+================================+
# | Section   | 1                   | See Supported Versions         |
# | 2.1       |                     | (Section 2.5.1.3.1) (MUST be   |
# |           |                     | "02" in version 2.0 Headers)   |
# +-----------+---------------------+--------------------------------+
# | Algorithm | 2                   | See Supported Algorithm Suites |
# | Suite ID  |                     | (../framework/algorithm-       |
# | (Section  |                     | suites.md#supported-algorithm- |
# | 2.5.1.5)  |                     | suites)                        |
# +-----------+---------------------+--------------------------------+
# | Message   | 16                  | Bytes                          |
# | ID        |                     |                                |
# | (Section  |                     |                                |
# | 2.5.1.6)  |                     |                                |
# +-----------+---------------------+--------------------------------+
# | Section   | Variable.           | Section 2.5.1.7                |
# | 2.5.1.7   | Self-describing     |                                |
# |           | (Section 2.5.1.7).  |                                |
# +-----------+---------------------+--------------------------------+
# | Encrypted | Variable.           | Encrypted Data Keys            |
# | Data Keys | Determined by the   | (Section 2.5.1.8)              |
# | (Section  | number of encrypted |                                |
# | 2.5.1.8)  | data keys and the   |                                |
# |           | length of each.     |                                |
# +-----------+---------------------+--------------------------------+
# | Content   | 1                   | See Supported Types            |
# | Type      |                     | (Section 2.5.1.11.1)           |
# | (Section  |                     |                                |
# | 2.5.1.11) |                     |                                |
# +-----------+---------------------+--------------------------------+
# | Frame     | 4                   | UInt32                         |
# | Length    |                     |                                |
# | (Section  |                     |                                |
# | 2.5.2.3)  |                     |                                |
# +-----------+---------------------+--------------------------------+
# | Algorithm | Variable.           | See Algorithm Suite Data       |
# | Suite     | Determined by the   | (../framework/algorithm-       |
# | Data      | Algorithm Suite ID  | suites.md#algorithm-suite-     |
# | (Section  |                     | data)                          |
# | 2.5.2)    |                     |                                |
# +-----------+---------------------+--------------------------------+
# 
#                               Table 3

[[spec]]
level = "MUST"
quote = '''
+===========+=====================+================================+
| Field     | Length (bytes)      | Interpreted as                 |
+===========+=====================+================================+
| Section   | 1                   | See Supported Versions         |
| 2.1       |                     | (Section 2.5.1.3.1) (MUST be   |
|           |                     | "02" in version 2.0 Headers)   |
+-----------+---------------------+--------------------------------+
| Algorithm | 2                   | See Supported Algorithm Suites |
| Suite ID  |                     | (../framework/algorithm-       |
| (Section  |                     | suites.md#supported-algorithm- |
| 2.5.1.5)  |                     | suites)                        |
+-----------+---------------------+--------------------------------+
| Message   | 16                  | Bytes                          |
| ID        |                     |                                |
| (Section  |                     |                                |
| 2.5.1.6)  |                     |                                |
+-----------+---------------------+--------------------------------+
| Section   | Variable.
'''

