target = "compliance/data-format/message-header.txt#2.5"

# 2.5.  Structure
#
# The message header is a sequence of bytes that MUST be in big-endian
# format.  The following table describes the fields that form the
# header.  The bytes are appended in the order shown.
# 
#  +=======================+================+=======================+
#  | Field                 | Length (bytes) | Interpreted as        |
#  +=======================+================+=======================+
#  | Header Body           | Variable       | Header Body           |
#  | (Section 2.5.1)       |                | (Section 2.5.1)       |
#  +-----------------------+----------------+-----------------------+
#  | Header Authentication | Variable       | Header Authentication |
#  | (Section 2.5.3)       |                | (Section 2.5.3)       |
#  +-----------------------+----------------+-----------------------+
# 
#                               Table 1

[[spec]]
level = "MUST"
quote = '''
The message header is a sequence of bytes that MUST be in big-endian
format.
'''

