target = "compliance/framework/raw-aes-keyring.txt#2.5"

# 2.5.  Initialization
#
# On keyring initialization, the caller MUST provide the following:
# 
# *  Key Namespace (./keyring-interface.md#key-namespace)
# 
# *  Key Name (./keyring-interface.md#key-name)
# 
# *  Wrapping Key (Section 2.5.1)

[[spec]]
level = "MUST"
quote = '''
On keyring initialization, the caller MUST provide the following:
'''

