target = "compliance/framework/raw-aes-keyring.txt#2.6.1.2"

# 2.6.1.2.  Authentication Tag Length
#
# The length, in bits, of the authentication tag returned by the AES-
# GCM encryption.
# 
# This value MUST be 128.

[[spec]]
level = "MUST"
quote = '''
This value MUST be 128.
'''

