target = "compliance/framework/raw-aes-keyring.txt#2.6.1.3"

# 2.6.1.3.  IV Length
#
# The length, in bytes, of the initialization vector (IV) input into
# the AES-GCM encryption.
# 
# This value MUST be 12.

[[spec]]
level = "MUST"
quote = '''
This value MUST be 12.
'''

