target = "compliance/framework/raw-aes-keyring.txt#2.7.2"

# 2.7.2.  OnDecrypt
#
# OnDecrypt MUST take decryption materials (structures.md#decryption-
# materials) and a list of encrypted data keys
# (structures.md#encrypted-data-key) as input.
# 
# If the decryption materials already contain a plaintext data key, the
# keyring MUST fail and MUST NOT modify the decryption materials
# (structures.md#decryption-materials).
# 
# The keyring MUST attempt to serialize the decryption materials'
# (structures.md#decryption-materials) encryption context
# (structures.md#encryption-context-1) in the same format as the
# serialization of the message header AAD key value pairs (../data-
# format/message-header.md#key-value-pairs).  If the keyring cannot
# serialize the encryption context, OnDecrypt MUST fail.
# 
# The keyring MUST perform the following actions on each encrypted data
# key (structures.md#encrypted-data-key) in the input encrypted data
# key list, serially, until it successfully decrypts one.
# 
# For each encrypted data key (structures.md#encrypted-data-key), the
# keyring MUST first attempt to deserialize the serialized ciphertext
# (Section 2.6.2) to obtain the encrypted key (Section 2.6.2.1) and
# authentication tag (Section 2.6.2.2), and deserialize the serialized
# key provider info (Section 2.6.1) to obtain the key name (./keyring-
# interface.md#key-name), Section 2.6.1.4, IV length (Section 2.6.1.3),
# and authentication tag length (Section 2.6.1.2).
# 
# The keyring MUST attempt to decrypt the encrypted data key if and
# only if the following is true:
# 
# *  The Section 2.6.2 and key provider information (Section 2.6.1) are
#    successfully deserialized.
# 
# *  The key name obtained from the encrypted data key's key provider
#    information has a value equal to this keyring's key name
#    (./keyring-interface.md#key-name).
# 
# *  The key provider ID of the encrypted data key has a value equal to
#    this keyring's key namespace (./keyring-interface.md#key-
#    namespace).
# 
# *  The IV length (Section 2.6.1.3) obtained from the encrypted data
#    key's key provider information has a value equal to 12.
# 
# *  The authentication tag length (Section 2.6.1.2) obtained from the
#    key provider information has a value equal to 128.
# 
# If decrypting, the keyring MUST use AES-GCM with the following
# specifics:
# 
# *  It uses the encrypt key (Section 2.6.2.1) obtained from
#    deserialization as the AES-GCM input ciphertext.
# 
# *  It uses the authentication tag (Section 2.6.2.2) obtained from
#    deserialization as the AES-GCM input authentication tag.
# 
# *  It uses this keyring's wrapping key (Section 2.5.1) as the AES-GCM
#    cipher key.
# 
# *  It uses the Section 2.6.1.4 obtained from deserialization as the
#    AES-GCM IV.
# 
# *  It uses the serialized encryption context
#    (structures.md#encryption-context-1) as the AES-GCM AAD.
# 
# If a decryption succeeds, this keyring MUST add the resulting
# plaintext data key to the decryption materials and return the
# modified materials.
# 
# If no decryption succeeds, the keyring MUST fail and MUST NOT modify
# the decryption materials (structures.md#decryption-materials).

[[spec]]
level = "MUST"
quote = '''
OnDecrypt MUST take decryption materials (structures.md#decryption-
materials) and a list of encrypted data keys
(structures.md#encrypted-data-key) as input.
'''

[[spec]]
level = "MUST"
quote = '''
If the decryption materials already contain a plaintext data key, the
keyring MUST fail and MUST NOT modify the decryption materials
(structures.md#decryption-materials).
'''

[[spec]]
level = "MUST"
quote = '''
If the decryption materials already contain a plaintext data key, the
keyring MUST fail and MUST NOT modify the decryption materials
(structures.md#decryption-materials).
'''

[[spec]]
level = "MUST"
quote = '''
The keyring MUST attempt to serialize the decryption materials'
(structures.md#decryption-materials) encryption context
(structures.md#encryption-context-1) in the same format as the
serialization of the message header AAD key value pairs (../data-
format/message-header.md#key-value-pairs).
'''

[[spec]]
level = "MUST"
quote = '''
If the keyring cannot
serialize the encryption context, OnDecrypt MUST fail.
'''

[[spec]]
level = "MUST"
quote = '''
The keyring MUST perform the following actions on each encrypted data
key (structures.md#encrypted-data-key) in the input encrypted data
key list, serially, until it successfully decrypts one.
'''

[[spec]]
level = "MUST"
quote = '''
For each encrypted data key (structures.md#encrypted-data-key), the
keyring MUST first attempt to deserialize the serialized ciphertext
(Section 2.6.2) to obtain the encrypted key (Section 2.6.2.1) and
authentication tag (Section 2.6.2.2), and deserialize the serialized
key provider info (Section 2.6.1) to obtain the key name (./keyring-
interface.md#key-name), Section 2.6.1.4, IV length (Section 2.6.1.3),
and authentication tag length (Section 2.6.1.2).
'''

[[spec]]
level = "MUST"
quote = '''
The keyring MUST attempt to decrypt the encrypted data key if and
only if the following is true:
'''

[[spec]]
level = "MUST"
quote = '''
If decrypting, the keyring MUST use AES-GCM with the following
specifics:
'''

[[spec]]
level = "MUST"
quote = '''
If a decryption succeeds, this keyring MUST add the resulting
plaintext data key to the decryption materials and return the
modified materials.
'''

[[spec]]
level = "MUST"
quote = '''
If no decryption succeeds, the keyring MUST fail and MUST NOT modify
the decryption materials (structures.md#decryption-materials).
'''

[[spec]]
level = "MUST"
quote = '''
If no decryption succeeds, the keyring MUST fail and MUST NOT modify
the decryption materials (structures.md#decryption-materials).
'''

