target = "compliance/framework/default-cmm.txt#2.5"

# 2.5.  Initialization
#
# On default CMM initialization, the caller MUST provide the following
# value:
# 
# *  Section 2.5.1

[[spec]]
level = "MUST"
quote = '''
On default CMM initialization, the caller MUST provide the following
value:
'''

