target = "compliance/framework/default-cmm.txt#2.6.1"

# 2.6.1.  Get Encryption Materials
#
# This operation will add a key-value pair to the encryption context
# included in the encryption materials request (cmm-
# interface.md#encryption-materials-request) using the key "aws-crypto-
# public-key".  Adding the key "aws-crypto-public-key" SHOULD be done
# to a copy of the encryption context so that the caller's encryption
# context is not mutated.  If the encryption context included in the
# encryption materials request (cmm-interface.md#encryption-materials-
# request) already contains the "aws-crypto-public-key" key, this
# operation MUST fail rather than overwrite the associated value.
# 
# *  If the encryption materials request (cmm-interface.md#encryption-
#    materials-request) does not contain an algorithm suite, the
#    operation MUST add the default algorithm suite for the commitment
#    policy (../client-apis/client.md#commitment-policy) as the
#    algorithm suite in the encryption materials returned.
# 
# *  If the encryption materials request (cmm-interface.md#encryption-
#    materials-request) does contain an algorithm suite, the request
#    MUST fail if the algorithm suite is not supported by the
#    commitment policy (../client-apis/client.md#commitment-policy) on
#    the request.
# 
# *  If the encryption materials request (cmm-interface.md#encryption-
#    materials-request) does contain an algorithm suite, the encryption
#    materials returned MUST contain the same algorithm suite.
# 
# If the algorithm suite contains a signing algorithm (algorithm-
# suites.md#signature-algorithm), the default CMM MUST Generate a
# signing key (structures.md#signing-key).
# 
# If the algorithm suite contains a signing algorithm (algorithm-
# suites.md#signature-algorithm), the default CMM MUST Add the
# following key-value pair to the encryption context
# (structures.md#encryption-context):
# 
# *  The key MUST be the reserved name, "aws-crypto-public-key".
# 
# *  The value MUST be the base64-encoded public verification key.
# 
# On each call to Get Encryption Materials, the default CMM MUST make a
# call to its keyring's (Section 2.5.1) On Encrypt (keyring-
# interface.md#onencrypt) operation.
# 
# The default CMM MUST obtain the Plaintext Data Key from the Get
# Encryption Materials Response and include it in the encryption
# materials (structures.md#encryption-materials) returned.
# 
# The default CMM MUST obtain the Encrypted Data Keys
# (structures.md#encrypted-data-keys) from the Get Encryption Materials
# Response and include it in the encryption materials
# (structures.md#encryption-materials) returned.

[[spec]]
level = "SHOULD"
quote = '''
Adding the key "aws-crypto-public-key" SHOULD be done
to a copy of the encryption context so that the caller's encryption
context is not mutated.
'''

[[spec]]
level = "MUST"
quote = '''
If the encryption context included in the
encryption materials request (cmm-interface.md#encryption-materials-
request) already contains the "aws-crypto-public-key" key, this
operation MUST fail rather than overwrite the associated value.
'''

[[spec]]
level = "MUST"
quote = '''
*  If the encryption materials request (cmm-interface.md#encryption-
materials-request) does not contain an algorithm suite, the
operation MUST add the default algorithm suite for the commitment
policy (../client-apis/client.md#commitment-policy) as the
algorithm suite in the encryption materials returned.
'''

[[spec]]
level = "MUST"
quote = '''
*  If the encryption materials request (cmm-interface.md#encryption-
materials-request) does contain an algorithm suite, the request
MUST fail if the algorithm suite is not supported by the
commitment policy (../client-apis/client.md#commitment-policy) on
the request.
'''

[[spec]]
level = "MUST"
quote = '''
*  If the encryption materials request (cmm-interface.md#encryption-
materials-request) does contain an algorithm suite, the encryption
materials returned MUST contain the same algorithm suite.
'''

[[spec]]
level = "MUST"
quote = '''
If the algorithm suite contains a signing algorithm (algorithm-
suites.md#signature-algorithm), the default CMM MUST Generate a
signing key (structures.md#signing-key).
'''

[[spec]]
level = "MUST"
quote = '''
If the algorithm suite contains a signing algorithm (algorithm-
suites.md#signature-algorithm), the default CMM MUST Add the
following key-value pair to the encryption context
(structures.md#encryption-context):
'''

[[spec]]
level = "MUST"
quote = '''
*  The key MUST be the reserved name, "aws-crypto-public-key".
'''

[[spec]]
level = "MUST"
quote = '''
*  The value MUST be the base64-encoded public verification key.
'''

[[spec]]
level = "MUST"
quote = '''
On each call to Get Encryption Materials, the default CMM MUST make a
call to its keyring's (Section 2.5.1) On Encrypt (keyring-
interface.md#onencrypt) operation.
'''

[[spec]]
level = "MUST"
quote = '''
The default CMM MUST obtain the Plaintext Data Key from the Get
Encryption Materials Response and include it in the encryption
materials (structures.md#encryption-materials) returned.
'''

[[spec]]
level = "MUST"
quote = '''
The default CMM MUST obtain the Encrypted Data Keys
(structures.md#encrypted-data-keys) from the Get Encryption Materials
Response and include it in the encryption materials
(structures.md#encryption-materials) returned.
'''

