target = "compliance/framework/default-cmm.txt#2.7.2"

# 2.7.2.  Initialization
#
# In place of requiring the caller to provide a keyring (keyring-
# interface.md) on initialization:
# 
# On default CMM initialization, the caller MUST provide the following
# value:
# 
# *  Master Key Provider (master-key-provider-interface.md)

[[spec]]
level = "MUST"
quote = '''
On default CMM initialization, the caller MUST provide the following
value:
'''

