target = "compliance/framework/default-cmm.txt#2.7.3"

# 2.7.3.  Get Encryption Materials (master key provider)
#
# In place of calling its keyring's On Encrypt (keyring-
# interface.md#onencrypt) operation:
# 
# The default CMM MUST call its master key provider's Get Master Keys
# for Encryption (master-key-provider-interface.md#get-master-keys-for-
# encryption) operation to obtain a list of master keys to use.
# 
# If the master key provider does not identify which master key MUST
# generate the data key, the default CMM MUST use the first master key
# in the list for that purpose.  The default CMM MUST generate the data
# key using this master key's Generate Data Key (master-key-
# interface.md#generate-data-key) operation.
# 
# For each remaining master key, the default CMM MUST call the master
# key's Encrypt Data Key (master-key-interface.md#encrypt-data-key)
# operation with the plaintext data key.

[[spec]]
level = "MUST"
quote = '''
The default CMM MUST call its master key provider's Get Master Keys
for Encryption (master-key-provider-interface.md#get-master-keys-for-
encryption) operation to obtain a list of master keys to use.
'''

[[spec]]
level = "MUST"
quote = '''
If the master key provider does not identify which master key MUST
generate the data key, the default CMM MUST use the first master key
in the list for that purpose.
'''

[[spec]]
level = "MUST"
quote = '''
If the master key provider does not identify which master key MUST
generate the data key, the default CMM MUST use the first master key
in the list for that purpose.
'''

[[spec]]
level = "MUST"
quote = '''
The default CMM MUST generate the data
key using this master key's Generate Data Key (master-key-
interface.md#generate-data-key) operation.
'''

[[spec]]
level = "MUST"
quote = '''
For each remaining master key, the default CMM MUST call the master
key's Encrypt Data Key (master-key-interface.md#encrypt-data-key)
operation with the plaintext data key.
'''

