target = "compliance/framework/raw-rsa-keyring.txt#2.5"

# 2.5.  Initialization
#
# On keyring initialization, the caller MUST provide the following:
# 
# *  Key Namespace (./keyring-interface.md#key-namespace)
# 
# *  Key Name (./keyring-interface.md#key-name)
# 
# *  Padding Scheme (Section 2.5.1)
# 
# *  Public Key (Section 2.5.2) and/or Private Key (Section 2.5.3)

[[spec]]
level = "MUST"
quote = '''
On keyring initialization, the caller MUST provide the following:
'''

