target = "compliance/framework/raw-rsa-keyring.txt#2.5.1"

# 2.5.1.  Padding Scheme
#
# The RSA padding scheme to use with this keyring.
# 
# This value MUST correspond with one of the supported padding schemes
# (Section 2.5.1.1).
# 
# If the padding scheme uses MGF1 Padding, the hash function used as
# part of MGF1 MUST be the same hash function used to hash the
# plaintext data key.

[[spec]]
level = "MUST"
quote = '''
This value MUST correspond with one of the supported padding schemes
(Section 2.5.1.1).
'''

[[spec]]
level = "MUST"
quote = '''
If the padding scheme uses MGF1 Padding, the hash function used as
part of MGF1 MUST be the same hash function used to hash the
plaintext data key.
'''

