target = "compliance/framework/raw-rsa-keyring.txt#2.5.2"

# 2.5.2.  Public Key
#
# The RSA public key used by this keyring to encrypt data keys.
# 
# The public key MUST follow the RSA specification for public keys
# (Section 2.4.2).  The raw RSA keyring SHOULD support loading PEM
# encoded X.509 SubjectPublicKeyInfo structures
# (https://tools.ietf.org/html/rfc5280#section-4.1) as public keys.

[[spec]]
level = "MUST"
quote = '''
The public key MUST follow the RSA specification for public keys
(Section 2.4.2).
'''

[[spec]]
level = "SHOULD"
quote = '''
The raw RSA keyring SHOULD support loading PEM
encoded X.509 SubjectPublicKeyInfo structures
(https://tools.ietf.org/html/rfc5280#section-4.1) as public keys.
'''

