target = "compliance/framework/raw-rsa-keyring.txt#2.5.1.1"

# 2.5.1.1.  Supported Padding Schemes
#
# The following padding schemes are currently defined:
# 
# *  PKCS1 v1.5 Padding (https://tools.ietf.org/html/rfc8017#section-
#    7.2)
# 
# *  OAEP with SHA-1 and MGF1 with SHA-1 Padding
#    (https://tools.ietf.org/html/rfc8017#section-7.1)
# 
# *  OAEP with SHA-256 and MGF1 with SHA-256 Padding
#    (https://tools.ietf.org/html/rfc8017#section-7.1)
# 
# *  OAEP with SHA-384 and MGF1 with SHA-384 Padding
#    (https://tools.ietf.org/html/rfc8017#section-7.1)
# 
# *  OAEP with SHA-512 and MGF1 with SHA-512 Padding
#    (https://tools.ietf.org/html/rfc8017#section-7.1)
# 
# This keyring MUST NOT use a padding scheme outside those defined
# above.

[[spec]]
level = "MUST"
quote = '''
This keyring MUST NOT use a padding scheme outside those defined
above.
'''

