target = "compliance/framework/raw-rsa-keyring.txt#2.6.2"

# 2.6.2.  OnDecrypt
#
# OnDecrypt MUST fail if this keyring does not have a specified private
# key (Section 2.5.3).
# 
# OnDecrypt MUST take decryption materials (structures.md#decryption-
# materials) and a list of encrypted data keys
# (structures.md#encrypted-data-key) as input.
# 
# If the decryption materials already contain a plaintext data key, the
# keyring MUST fail and MUST NOT modify the decryption materials
# (structures.md#decryption-materials).
# 
# The keyring MUST attempt to decrypt the input encrypted data keys, in
# list order, until it successfully decrypts one.
# 
# For each encrypted data key, the keyring MUST attempt to decrypt the
# encrypted data key into plaintext using RSA if and only if the
# following is true:
# 
# *  The encrypted data key's key provider information
#    (structures.md#key-provider-information). has a value equal to
#    this keyring's key name (keyring-interface.md#key-name).
# 
# *  The encrypted data key's key provider ID (structures.md#key-
#    provider-id) has a value equal to this keyring's key namespace
#    (keyring-interface.md#key-namespace).
# 
# The keyring performs RSA decryption with the following specifics:
# 
# *  This keyring's private key (Section 2.5.3) is the RSA private key.
# 
# *  This keyring's padding scheme (Section 2.5.1.1) is the RSA padding
#    scheme.
# 
# *  An encrypted data key's ciphertext (structures.md#ciphertext) is
#    the input ciphertext to RSA decryption.
# 
# If any decryption succeeds, this keyring MUST immediately return the
# input decryption materials (structures.md#decryption-materials),
# modified in the following ways:
# 
# *  The output of RSA decryption is set as the decryption material's
#    plaintext data key.
# 
# If no decryption succeeds, the keyring MUST fail and MUST NOT modify
# the decryption materials (structures.md#decryption-materials).

[[spec]]
level = "MUST"
quote = '''
OnDecrypt MUST fail if this keyring does not have a specified private
key (Section 2.5.3).
'''

[[spec]]
level = "MUST"
quote = '''
OnDecrypt MUST take decryption materials (structures.md#decryption-
materials) and a list of encrypted data keys
(structures.md#encrypted-data-key) as input.
'''

[[spec]]
level = "MUST"
quote = '''
If the decryption materials already contain a plaintext data key, the
keyring MUST fail and MUST NOT modify the decryption materials
(structures.md#decryption-materials).
'''

[[spec]]
level = "MUST"
quote = '''
If the decryption materials already contain a plaintext data key, the
keyring MUST fail and MUST NOT modify the decryption materials
(structures.md#decryption-materials).
'''

[[spec]]
level = "MUST"
quote = '''
The keyring MUST attempt to decrypt the input encrypted data keys, in
list order, until it successfully decrypts one.
'''

[[spec]]
level = "MUST"
quote = '''
For each encrypted data key, the keyring MUST attempt to decrypt the
encrypted data key into plaintext using RSA if and only if the
following is true:
'''

[[spec]]
level = "MUST"
quote = '''
If any decryption succeeds, this keyring MUST immediately return the
input decryption materials (structures.md#decryption-materials),
modified in the following ways:
'''

[[spec]]
level = "MUST"
quote = '''
If no decryption succeeds, the keyring MUST fail and MUST NOT modify
the decryption materials (structures.md#decryption-materials).
'''

[[spec]]
level = "MUST"
quote = '''
If no decryption succeeds, the keyring MUST fail and MUST NOT modify
the decryption materials (structures.md#decryption-materials).
'''

