target = "compliance/data-format/message.txt#2.3"

# 2.3.  Structure
#
# A message is a sequence of bytes that is the serialization of the
# following, in order:
# 
# *  Message Header (message-header.md)
# 
# *  Message Body (message-body.md)
# 
# If the message header (message-header.md) contains an algorithm suite
# (../framework/algorithm-suites.md) in the algorithm suite ID
# (message-header.md#algorithm-suite-id) field that contains a
# signature algorithm (../framework/algorithm-suites.md#signature-
# algorithm), the message MUST also contain a message footer (message-
# footer.md), serialized after the message body (message-body.md).

[[spec]]
level = "MUST"
quote = '''
If the message header (message-header.md) contains an algorithm suite
(../framework/algorithm-suites.md) in the algorithm suite ID
(message-header.md#algorithm-suite-id) field that contains a
signature algorithm (../framework/algorithm-suites.md#signature-
algorithm), the message MUST also contain a message footer (message-
footer.md), serialized after the message body (message-body.md).
'''

