target = "compliance/data-format/message-body-aad.txt#2.4.3"

# 2.4.3.  Sequence Number
#
# The sequence number of the data this message body AAD belongs to.
# For framed data (message-body.md#framed-data), the value of this
# field MUST be the frame sequence number (message-body.md#sequence-
# number).  For non-framed data (message-body.md#non-framed-data), the
# value of this field MUST be "1".

[[spec]]
level = "MUST"
quote = '''
For framed data (message-body.md#framed-data), the value of this
field MUST be the frame sequence number (message-body.md#sequence-
number).
'''

[[spec]]
level = "MUST"
quote = '''
For non-framed data (message-body.md#non-framed-data), the
value of this field MUST be "1".
'''

