target = "compliance/data-format/message-body-aad.txt#2.4.2"

# 2.4.2.  Body AAD Content
#
# An identifier for the content type of the data this message body AAD
# is associated with.
# 
# This value depends on the content type (message-header.md#content-
# type) of the message (message.md):
# 
# *  Non-framed data (message-body.md#non-framed-data) MUST use the
#    value "AWSKMSEncryptionClient Single Block".
# 
# *  The regular frames (message-body.md#regular-frame) in framed data
#    (message-body.md#framed-data) MUST use the value
#    "AWSKMSEncryptionClient Frame".
# 
# *  The final frame (message-body.md#final-frame) in framed data
#    (message-body.md#framed-data) MUST use the value
#    "AWSKMSEncryptionClient Final Frame".

[[spec]]
level = "MUST"
quote = '''
*  Non-framed data (message-body.md#non-framed-data) MUST use the
value "AWSKMSEncryptionClient Single Block".
'''

[[spec]]
level = "MUST"
quote = '''
*  The regular frames (message-body.md#regular-frame) in framed data
(message-body.md#framed-data) MUST use the value
"AWSKMSEncryptionClient Frame".
'''

[[spec]]
level = "MUST"
quote = '''
*  The final frame (message-body.md#final-frame) in framed data
(message-body.md#framed-data) MUST use the value
"AWSKMSEncryptionClient Final Frame".
'''

