target = "compliance/data-format/message-body.txt#2.5.2.2"

# 2.5.2.2.  Final Frame
#
# Framed data MUST contain exactly one final frame.  The final frame
# MUST be the last frame.
# 
# The length of the plaintext to be encrypted in the Final Frame MUST
# be greater than or equal to 0 and less than or equal to the Frame
# Length (message-header.md#frame-length).
# 
# *  When the length of the Plaintext is not an exact multiple of the
#    Frame Length, any remaining data is encrypted into the Final
#    Frame.
# 
# *  When the length of the Plaintext is an exact multiple of the Frame
#    Length (including if it is equal to the frame length), the Final
#    Frame encrypted content length SHOULD be equal to the frame length
#    but MAY be 0.
# 
# *  When the length of the Plaintext is less than the Frame Length,
#    the body MUST contain exactly one frame and that frame MUST be a
#    Final Frame.
# 
# For example, in the case that the length of the Plaintext is equal to
# the Frame Length, there are two acceptable cases:
# 
# *  The body contains exactly one frame, the final frame, with a
#    content length equal to the plaintext length.
# 
# *  The body contains two frames.  The first frame is a regular frame,
#    and the second frame is the final frame with a content length of
#    0.
# 
# The following describes the fields that form the Final Frame Body
# Structure.  The bytes are appended in the order shown.
# 
#     +================+===========================+=============+
#     | Field          | Length (bytes)            | Interpreted |
#     |                |                           | as          |
#     +================+===========================+=============+
#     | Sequence       | 4                         | Bytes       |
#     | Number End     |                           |             |
#     | (Section       |                           |             |
#     | 2.5.2.2.1)     |                           |             |
#     +----------------+---------------------------+-------------+
#     | Sequence       | 4                         | UInt32      |
#     | Number         |                           |             |
#     | (Section       |                           |             |
#     | 2.5.2.1.1)     |                           |             |
#     +----------------+---------------------------+-------------+
#     | Section        | IV Length (message-       | Bytes       |
#     | 2.5.1.1        | header.md#iv-length)      |             |
#     +----------------+---------------------------+-------------+
#     | Encrypted      | 4                         | UInt32      |
#     | Content Length |                           |             |
#     | (Section       |                           |             |
#     | 2.5.2.2.4)     |                           |             |
#     +----------------+---------------------------+-------------+
#     | Encrypted      | Variable                  | Bytes       |
#     | Content        |                           |             |
#     | (Section       |                           |             |
#     | 2.5.1.3)       |                           |             |
#     +----------------+---------------------------+-------------+
#     | Authentication | Algorithm suite ID's      | Bytes       |
#     | Tag (Section   | Authentication Tag Length |             |
#     | 2.5.1.4)       | (../framework/algorithm-  |             |
#     |                | suites.md#authentication- |             |
#     |                | tag-length)               |             |
#     +----------------+---------------------------+-------------+
# 
#                               Table 3

[[spec]]
level = "MUST"
quote = '''
Framed data MUST contain exactly one final frame.
'''

[[spec]]
level = "MUST"
quote = '''
The final frame
MUST be the last frame.
'''

[[spec]]
level = "MUST"
quote = '''
The length of the plaintext to be encrypted in the Final Frame MUST
be greater than or equal to 0 and less than or equal to the Frame
Length (message-header.md#frame-length).
'''

[[spec]]
level = "SHOULD"
quote = '''
*  When the length of the Plaintext is an exact multiple of the Frame
Length (including if it is equal to the frame length), the Final
Frame encrypted content length SHOULD be equal to the frame length
but MAY be 0.
'''

[[spec]]
level = "MUST"
quote = '''
*  When the length of the Plaintext is less than the Frame Length,
the body MUST contain exactly one frame and that frame MUST be a
Final Frame.
'''

[[spec]]
level = "MUST"
quote = '''
*  When the length of the Plaintext is less than the Frame Length,
the body MUST contain exactly one frame and that frame MUST be a
Final Frame.
'''

