target = "compliance/data-format/message-body.txt#2.5.1.2"

# 2.5.1.2.  Encrypted Content Length
#
# The length of the encrypted content.  The length MUST NOT be greater
# than "2^36 - 32", or 64 gibibytes (64 GiB), due to restrictions
# imposed by the implemented algorithms (../framework/algorithm-
# suites.md).

[[spec]]
level = "MUST"
quote = '''
The length MUST NOT be greater
than "2^36 - 32", or 64 gibibytes (64 GiB), due to restrictions
imposed by the implemented algorithms (../framework/algorithm-
suites.md).
'''

