target = "compliance/data-format/message-body.txt#2.5.2.2.1"

# 2.5.2.2.1.  Sequence Number End
#
# An indicator for the Final Frame.  The value MUST be encoded as the 4
# bytes "FF FF FF FF" in hexadecimal notation.

[[spec]]
level = "MUST"
quote = '''
The value MUST be encoded as the 4
bytes "FF FF FF FF" in hexadecimal notation.
'''

