target = "compliance/data-format/message-body.txt#2.5.2.1.4"

# 2.5.2.1.4.  Authentication Tag
#
# The authentication value for the frame.  The authentication tag
# length MUST be equal to the authentication tag length of the
# algorithm suite specified by the Algorithm Suite ID (message-
# header.md#algorithm-suite-id) field.

[[spec]]
level = "MUST"
quote = '''
The authentication tag
length MUST be equal to the authentication tag length of the
algorithm suite specified by the Algorithm Suite ID (message-
header.md#algorithm-suite-id) field.
'''

