target = "compliance/data-format/message-body.txt#2.5.2.2.2"

# 2.5.2.2.2.  Sequence Number
#
# The Frame Sequence Number.  It is an incremental counter number for
# the frames.  Framed Data MUST start at Sequence Number 1.  Subsequent
# frames MUST be in order and MUST contain an increment of 1 from the
# previous frame.  The Final Frame Sequence number MUST be equal to the
# total number of frames in the Framed Data.

[[spec]]
level = "MUST"
quote = '''
Framed Data MUST start at Sequence Number 1.
'''

[[spec]]
level = "MUST"
quote = '''
Subsequent
frames MUST be in order and MUST contain an increment of 1 from the
previous frame.
'''

[[spec]]
level = "MUST"
quote = '''
Subsequent
frames MUST be in order and MUST contain an increment of 1 from the
previous frame.
'''

[[spec]]
level = "MUST"
quote = '''
The Final Frame Sequence number MUST be equal to the
total number of frames in the Framed Data.
'''

