target = "compliance/framework/keyring-interface.txt#2.3"

# 2.3.  Overview
#
# Keyrings are responsible for the generation, encryption, and
# decryption of data keys.
# 
# The keyring interface specified in this document describes the
# interface all keyrings MUST implement.

[[spec]]
level = "MUST"
quote = '''
The keyring interface specified in this document describes the
interface all keyrings MUST implement.
'''

