target = "compliance/framework/keyring-interface.txt#2.4.4"

# 2.4.4.  key provider ID
#
# An output value returned by a keyring on encrypt as part of an
# encrypted data key structure that identifies the grouping or
# categorization for a keyring that can fulfill this decryption
# contract.
# 
# The key provider ID MUST be a binary value and SHOULD be equal to a
# UTF-8 encoding of the key namespace.
# 
# This value MUST NOT be "aws-kms" unless this encrypted data key was
# produced by the AWS KMS Keyring (kms-keyring.md).

[[spec]]
level = "MUST"
quote = '''
The key provider ID MUST be a binary value and SHOULD be equal to a
UTF-8 encoding of the key namespace.
'''

[[spec]]
level = "MUST"
quote = '''
This value MUST NOT be "aws-kms" unless this encrypted data key was
produced by the AWS KMS Keyring (kms-keyring.md).
'''

