target = "compliance/framework/keyring-interface.txt#2.4.2"

# 2.4.2.  key namespace
#
# A configuration value for a keyring that identifies the grouping or
# categorization for the wrapping keys that the keyring can access.
# 
# The key namespace MUST be a string value.

[[spec]]
level = "MUST"
quote = '''
The key namespace MUST be a string value.
'''

