target = "compliance/framework/keyring-interface.txt#2.6.2"

# 2.6.2.  OnDecrypt
#
# This interface takes decryption materials (structures.md#decryption-
# materials) and a list of encrypted data keys
# (structures.md#encrypted-data-key) as input and MAY modify it with
# the following behavior:
# 
# *  Decrypt data key (Section 2.6.2.1)
# 
# If the decryption materials already contain a plaintext data key, the
# keyring MUST fail and MUST NOT modify the decryption materials
# (structures.md#decryption-materials).
# 
# If this keyring attempted the above behavior, and succeeded, it MUST
# output the modified decryption materials (structures.md#decryption-
# materials).
# 
# If the keyring did not attempt the above behavior, the keyring MUST
# fail and MUST NOT modify the decryption materials
# (structures.md#decryption-materials).

[[spec]]
level = "MAY"
quote = '''
This interface takes decryption materials (structures.md#decryption-
materials) and a list of encrypted data keys
(structures.md#encrypted-data-key) as input and MAY modify it with
the following behavior:
'''

[[spec]]
level = "MUST"
quote = '''
If the decryption materials already contain a plaintext data key, the
keyring MUST fail and MUST NOT modify the decryption materials
(structures.md#decryption-materials).
'''

[[spec]]
level = "MUST"
quote = '''
If the decryption materials already contain a plaintext data key, the
keyring MUST fail and MUST NOT modify the decryption materials
(structures.md#decryption-materials).
'''

[[spec]]
level = "MUST"
quote = '''
If this keyring attempted the above behavior, and succeeded, it MUST
output the modified decryption materials (structures.md#decryption-
materials).
'''

[[spec]]
level = "MUST"
quote = '''
If the keyring did not attempt the above behavior, the keyring MUST
fail and MUST NOT modify the decryption materials
(structures.md#decryption-materials).
'''

[[spec]]
level = "MUST"
quote = '''
If the keyring did not attempt the above behavior, the keyring MUST
fail and MUST NOT modify the decryption materials
(structures.md#decryption-materials).
'''

