target = "compliance/framework/keyring-interface.txt#2.6.2.1"

# 2.6.2.1.  Decrypt Data Key
#
# If the encryption materials do contain a plaintext data key,
# OnDecrypt MUST NOT decrypt a data key.  If the decryption materials
# (structures.md#decryption-materials) do not include a plaintext data
# key, OnDecrypt MAY decrypt a data key.
# 
# The decrypt data key MAY modify the following fields in the
# decryption materials (structures.md#decryption-materials):
# 
# *  Plaintext data key (structures.md#plaintext-data-key-1)
# 
# To perform this behavior, the keyring attempts to retrieve a
# plaintext data key from the input list of encrypted data keys
# (structures.md#encrypted-data-key).
# 
# If the keyring is able to succesfully get at least one plaintext data
# key from any encrypted data key (structures.md#encrypted-data-key)
# and the decryption materials (structures.md#decryption-materials)
# still do not include a plaintext data key, it SHOULD set one
# resulting plaintext data key on the decryption materials
# (structures.md#decryption-materials).
# 
# If the keyring is unable to get any plaintext data key using the
# input encrypted data keys (structures.md#encrypted-data-key), the
# keyring MUST NOT not update the decryption materials
# (structures.md#decryption-materials).

[[spec]]
level = "MUST"
quote = '''
If the encryption materials do contain a plaintext data key,
OnDecrypt MUST NOT decrypt a data key.
'''

[[spec]]
level = "MAY"
quote = '''
If the decryption materials
(structures.md#decryption-materials) do not include a plaintext data
key, OnDecrypt MAY decrypt a data key.
'''

[[spec]]
level = "MAY"
quote = '''
The decrypt data key MAY modify the following fields in the
decryption materials (structures.md#decryption-materials):
'''

[[spec]]
level = "SHOULD"
quote = '''
If the keyring is able to succesfully get at least one plaintext data
key from any encrypted data key (structures.md#encrypted-data-key)
and the decryption materials (structures.md#decryption-materials)
still do not include a plaintext data key, it SHOULD set one
resulting plaintext data key on the decryption materials
(structures.md#decryption-materials).
'''

[[spec]]
level = "MUST"
quote = '''
If the keyring is unable to get any plaintext data key using the
input encrypted data keys (structures.md#encrypted-data-key), the
keyring MUST NOT not update the decryption materials
(structures.md#decryption-materials).
'''

