target = "compliance/framework/keyring-interface.txt#2.6.1"

# 2.6.1.  OnEncrypt
#
# This interface takes encryption materials (structures.md#encryption-
# materials) as input and MAY modify it with any of the following
# behaviors:
# 
# *  Generate data key (Section 2.6.1.1)
# 
# *  Encrypt data key (Section 2.6.1.2)
# 
# If this keyring attempted any of the above behaviors, and
# successfully completed those behaviors, it MUST output the modified
# encryption materials (structures.md#encryption-materials).
# 
# If the keyring did not attempt any of the above behaviors, it MUST
# fail and it MUST NOT modify the encryption materials
# (structures.md#encryption-materials).

[[spec]]
level = "MAY"
quote = '''
This interface takes encryption materials (structures.md#encryption-
materials) as input and MAY modify it with any of the following
behaviors:
'''

[[spec]]
level = "MUST"
quote = '''
If this keyring attempted any of the above behaviors, and
successfully completed those behaviors, it MUST output the modified
encryption materials (structures.md#encryption-materials).
'''

[[spec]]
level = "MUST"
quote = '''
If the keyring did not attempt any of the above behaviors, it MUST
fail and it MUST NOT modify the encryption materials
(structures.md#encryption-materials).
'''

[[spec]]
level = "MUST"
quote = '''
If the keyring did not attempt any of the above behaviors, it MUST
fail and it MUST NOT modify the encryption materials
(structures.md#encryption-materials).
'''

