target = "compliance/framework/keyring-interface.txt#2.7"

# 2.7.  Security Considerations
#
# Keyring implementations SHOULD provide integrity guarantees for the
# encrypted data keys (structures.md#encrypted-data-key) they return on
# Section 2.6.1 such that tampered versions of those encrypted data
# keys, if input into Section 2.6.2, are overwhelmingly likely to cause
# a decryption failure (i.e. the chance of a successful decryption in
# this case is negligible).
# 
# Such integrity guarantees SHOULD include the integrity of the
# encryption context (structures.md#encryption-context) such that, if
# the encryption context used as input to OnEncrypt to produce an
# encrypted data key is different than the encryption context input to
# OnDecrypt to decrypt that encrypted data key, the decryption is
# overwhelmingly likely to fail.
# 
# Users SHOULD use a keyring that protects wrapping keys and performs
# cryptographic operations within a secure boundary.  Examples are:
# 
# *  The built-in AWS KMS keyring (kms-keyring.md), which uses AWS Key
#    Management Service (AWS KMS) customer master keys (CMKs) that
#    never leave AWS KMS plaintext.
# 
# *  A custom keyring that uses wrapping keys that are stored in your
#    hardware security modules (HSMs)
# 
# *  A custom keyring protected by another master key service.
# 
# The raw AES keyring (raw-aes-keyring.md) and raw RSA keyring (raw-
# rsa-keyring.md) MAY be used, however users should refer to their
# specification for notes on their respective security considerations.

[[spec]]
level = "SHOULD"
quote = '''
Keyring implementations SHOULD provide integrity guarantees for the
encrypted data keys (structures.md#encrypted-data-key) they return on
Section 2.6.1 such that tampered versions of those encrypted data
keys, if input into Section 2.6.2, are overwhelmingly likely to cause
a decryption failure (i.e.
'''

[[spec]]
level = "SHOULD"
quote = '''
Such integrity guarantees SHOULD include the integrity of the
encryption context (structures.md#encryption-context) such that, if
the encryption context used as input to OnEncrypt to produce an
encrypted data key is different than the encryption context input to
OnDecrypt to decrypt that encrypted data key, the decryption is
overwhelmingly likely to fail.
'''

[[spec]]
level = "SHOULD"
quote = '''
Users SHOULD use a keyring that protects wrapping keys and performs
cryptographic operations within a secure boundary.
'''

[[spec]]
level = "MAY"
quote = '''
The raw AES keyring (raw-aes-keyring.md) and raw RSA keyring (raw-
rsa-keyring.md) MAY be used, however users should refer to their
specification for notes on their respective security considerations.
'''

