target = "compliance/framework/keyring-interface.txt#2.8.2"

# 2.8.2.  Why should I use Keyrings instead of Master Key Providers and
#
#      Master Keys?
# 
# Keyrings provide a simplified architecture over master keys and
# master key providers.  The keyring combines the similar
# responsibilities of master keys and master key providers into one
# concept, as well as removes all key management logic from
# cryptographic materials managers (cmm-interface.md).
# 
# Due to this simplified architecture, master keys and master key
# providers are going to be deprecated in the future, and new
# implementations SHOULD use keyrings.

[[spec]]
level = "SHOULD"
quote = '''
Due to this simplified architecture, master keys and master key
providers are going to be deprecated in the future, and new
implementations SHOULD use keyrings.
'''

