target = "compliance/framework/cmm-interface.txt#2.3"

# 2.3.  Overview
#
# The Cryptographic Materials Manager (CMM) assembles the cryptographic
# materials used to encrypt the message (../data-format/message.md) and
# decrypt the encrypted messages.  The CMM interface describes the
# interface that all CMMs MUST implement.

[[spec]]
level = "MUST"
quote = '''
The CMM interface describes the
interface that all CMMs MUST implement.
'''

