target = "compliance/framework/cmm-interface.txt#2.5"

# 2.5.  Supported CMMs
#
# The AWS Encryption SDK provides the following built-in CMM types:
# 
# *  Default CMM (default-cmm.md)
# 
# *  Caching CMM (caching-cmm.md)
# 
# Note: A user MAY create their own custom CMM.

[[spec]]
level = "MAY"
quote = '''
Note: A user MAY create their own custom CMM.
'''

