target = "compliance/framework/cmm-interface.txt#2.6.1.1"

# 2.6.1.1.  Encryption Materials Request
#
# This is the input to the get encryption materials (Section 2.6.2.1)
# behavior.
# 
# The encryption materials request MUST include the following:
# 
# *  Encryption Context (structures.md#encryption-context)
# 
#    -  The encryption context provided MAY be empty.
# 
# *  Commitment Policy (../client-apis/client.md#commitment-policy)
# 
# The encryption request MAY include the following:
# 
# *  Algorithm Suite (algorithm-suites.md)
# 
# *  Max Plaintext Length
# 
#    -  This value represents the maximum length of the plaintext to be
#       encrypted using the returned materials.  The length of the
#       plaintext to be encrypted MUST not be larger than this value.

[[spec]]
level = "MUST"
quote = '''
The encryption materials request MUST include the following:
'''

[[spec]]
level = "MAY"
quote = '''
-  The encryption context provided MAY be empty.
'''

[[spec]]
level = "MAY"
quote = '''
The encryption request MAY include the following:
'''

[[spec]]
level = "MUST"
quote = '''
The length of the
plaintext to be encrypted MUST not be larger than this value.
'''

