target = "compliance/framework/cmm-interface.txt#2.6.1.2"

# 2.6.1.2.  Decrypt Materials Request
#
# This is the input to the decrypt materials (Section 2.6.2.2)
# behavior.
# 
# The decrypt materials request MUST include the following:
# 
# *  Algorithm Suite (algorithm-suites.md)
# 
# *  Encrypted Data Keys (structures.md#encrypted-data-keys)
# 
# *  Encryption Context (structures.md#encryption-context)
# 
#    -  The encryption context provided MAY be empty.

[[spec]]
level = "MUST"
quote = '''
The decrypt materials request MUST include the following:
'''

[[spec]]
level = "MAY"
quote = '''
-  The encryption context provided MAY be empty.
'''

