target = "compliance/framework/aws-kms/aws-kms-mrk-aware-symmetric-keyring.txt#2.5"

# 2.5.  Interface
#
# MUST implement the AWS Encryption SDK Keyring interface (../keyring-
# interface.md#interface)

[[spec]]
level = "MUST"
quote = '''
MUST implement the AWS Encryption SDK Keyring interface (../keyring-
interface.md#interface)
'''

