target = "compliance/framework/aws-kms/aws-kms-mrk-aware-symmetric-keyring.txt#2.7"

# 2.7.  OnEncrypt
#
# OnEncrypt MUST take encryption materials (structures.md#encryption-
# materials) as input.
# 
# If the input encryption materials (structures.md#encryption-
# materials) do not contain a plaintext data key OnEncrypt MUST attempt
# to generate a new plaintext data key by calling AWS KMS
# GenerateDataKey (https://docs.aws.amazon.com/kms/latest/APIReference/
# API_GenerateDataKey.html).
# 
# If the keyring calls AWS KMS GenerateDataKeys, it MUST use the
# configured AWS KMS client to make the call.  The keyring MUST call
# AWS KMS GenerateDataKeys with a request constructed as follows:
# 
# *  "KeyId": this keyring's KMS key identifier.
# 
# *  "NumberOfBytes": the key derivation input length (algorithm-
#    suites.md#key-derivation-input-length) specified by the algorithm
#    suite (algorithm-suites.md) included in the input encryption
#    materials (structures.md#encryption-materials).
# 
# *  "EncryptionContext": the encryption context
#    (structures.md#encryption-context) included in the input
#    encryption materials (structures.md#encryption-materials).
# 
# *  "GrantTokens": this keyring's grant tokens
#    (https://docs.aws.amazon.com/kms/latest/developerguide/
#    concepts.html#grant_token)
# 
# If the call to AWS KMS GenerateDataKey
# (https://docs.aws.amazon.com/kms/latest/APIReference/
# API_GenerateDataKey.html) does not succeed, OnEncrypt MUST NOT modify
# the encryption materials (structures.md#encryption-materials) and
# MUST fail.
# 
# If the Generate Data Key call succeeds, OnEncrypt MUST verify that
# the response "Plaintext" length matches the specification of the
# algorithm suite (algorithm-suites.md)'s Key Derivation Input Length
# field.  The Generate Data Key response's "KeyId" MUST be A valid AWS
# KMS key ARN (aws-kms-key-arn.md#identifying-an-aws-kms-multi-region-
# key).  If verified, OnEncrypt MUST do the following with the response
# from AWS KMS GenerateDataKey
# (https://docs.aws.amazon.com/kms/latest/APIReference/
# API_GenerateDataKey.html):
# 
# *  set the plaintext data key on the encryption materials
#    (structures.md#encryption-materials) as the response "Plaintext".
# 
# *  append a new encrypted data key (structures.md#encrypted-data-key)
#    to the encrypted data key list in the encryption materials
#    (structures.md#encryption-materials), constructed as follows:
# 
#    -  the ciphertext (structures.md#ciphertext) is the response
#       "CiphertextBlob".
# 
#    -  the key provider id (structures.md#key-provider-id) is "aws-
#       kms".
# 
#    -  the key provider information (structures.md#key-provider-
#       information) is the response "KeyId".
# 
# *  OnEncrypt MUST output the modified encryption materials
#    (structures.md#encryption-materials)
# 
# Given a plaintext data key in the encryption materials
# (structures.md#encryption-materials), OnEncrypt MUST attempt to
# encrypt the plaintext data key using the configured AWS KMS key
# identifier.
# 
# The keyring MUST call AWS KMS Encrypt
# (https://docs.aws.amazon.com/kms/latest/APIReference/
# API_Encrypt.html) using the configured AWS KMS client.  The keyring
# MUST AWS KMS Encrypt call with a request constructed as follows:
# 
# *  "KeyId": The configured AWS KMS key identifier.
# 
# *  "PlaintextDataKey": the plaintext data key in the encryption
#    materials (structures.md#encryption-materials).
# 
# *  "EncryptionContext": the encryption context
#    (structures.md#encryption-context) included in the input
#    encryption materials (structures.md#encryption-materials).
# 
# *  "GrantTokens": this keyring's grant tokens
#    (https://docs.aws.amazon.com/kms/latest/developerguide/
#    concepts.html#grant_token)
# 
# If the call to AWS KMS Encrypt
# (https://docs.aws.amazon.com/kms/latest/APIReference/
# API_Encrypt.html) does not succeed, OnEncrypt MUST fail.
# 
# If the Encrypt call succeeds The response's "KeyId" MUST be A valid
# AWS KMS key ARN (aws-kms-key-arn.md#identifying-an-aws-kms-multi-
# region-key).  If verified, OnEncrypt MUST do the following with the
# response from AWS KMS Encrypt
# (https://docs.aws.amazon.com/kms/latest/APIReference/
# API_Encrypt.html):
# 
# *  append a new encrypted data key (structures.md#encrypted-data-key)
#    to the encrypted data key list in the encryption materials
#    (structures.md#encryption-materials), constructed as follows:
# 
#    -  The ciphertext (structures.md#ciphertext) is the response
#       "CiphertextBlob".
# 
#    -  The key provider id (structures.md#key-provider-id) is "aws-
#       kms".
# 
#    -  The key provider information (structures.md#key-provider-
#       information) is the response "KeyId".  Note that the "KeyId" in
#       the response is always in key ARN format.
# 
# If all Encrypt calls succeed, OnEncrypt MUST output the modified
# encryption materials (structures.md#encryption-materials).

[[spec]]
level = "MUST"
quote = '''
OnEncrypt MUST take encryption materials (structures.md#encryption-
materials) as input.
'''

[[spec]]
level = "MUST"
quote = '''
If the input encryption materials (structures.md#encryption-
materials) do not contain a plaintext data key OnEncrypt MUST attempt
to generate a new plaintext data key by calling AWS KMS
GenerateDataKey (https://docs.aws.amazon.com/kms/latest/APIReference/
API_GenerateDataKey.html).
'''

[[spec]]
level = "MUST"
quote = '''
If the keyring calls AWS KMS GenerateDataKeys, it MUST use the
configured AWS KMS client to make the call.
'''

[[spec]]
level = "MUST"
quote = '''
The keyring MUST call
AWS KMS GenerateDataKeys with a request constructed as follows:
'''

[[spec]]
level = "MUST"
quote = '''
If the call to AWS KMS GenerateDataKey
(https://docs.aws.amazon.com/kms/latest/APIReference/
API_GenerateDataKey.html) does not succeed, OnEncrypt MUST NOT modify
the encryption materials (structures.md#encryption-materials) and
MUST fail.
'''

[[spec]]
level = "MUST"
quote = '''
If the call to AWS KMS GenerateDataKey
(https://docs.aws.amazon.com/kms/latest/APIReference/
API_GenerateDataKey.html) does not succeed, OnEncrypt MUST NOT modify
the encryption materials (structures.md#encryption-materials) and
MUST fail.
'''

[[spec]]
level = "MUST"
quote = '''
If the Generate Data Key call succeeds, OnEncrypt MUST verify that
the response "Plaintext" length matches the specification of the
algorithm suite (algorithm-suites.md)'s Key Derivation Input Length
field.
'''

[[spec]]
level = "MUST"
quote = '''
The Generate Data Key response's "KeyId" MUST be A valid AWS
KMS key ARN (aws-kms-key-arn.md#identifying-an-aws-kms-multi-region-
key).
'''

[[spec]]
level = "MUST"
quote = '''
If verified, OnEncrypt MUST do the following with the response
from AWS KMS GenerateDataKey
(https://docs.aws.amazon.com/kms/latest/APIReference/
API_GenerateDataKey.html):
'''

[[spec]]
level = "MUST"
quote = '''
*  OnEncrypt MUST output the modified encryption materials
(structures.md#encryption-materials)
'''

[[spec]]
level = "MUST"
quote = '''
Given a plaintext data key in the encryption materials
(structures.md#encryption-materials), OnEncrypt MUST attempt to
encrypt the plaintext data key using the configured AWS KMS key
identifier.
'''

[[spec]]
level = "MUST"
quote = '''
The keyring MUST call AWS KMS Encrypt
(https://docs.aws.amazon.com/kms/latest/APIReference/
API_Encrypt.html) using the configured AWS KMS client.
'''

[[spec]]
level = "MUST"
quote = '''
The keyring
MUST AWS KMS Encrypt call with a request constructed as follows:
'''

[[spec]]
level = "MUST"
quote = '''
If the call to AWS KMS Encrypt
(https://docs.aws.amazon.com/kms/latest/APIReference/
API_Encrypt.html) does not succeed, OnEncrypt MUST fail.
'''

[[spec]]
level = "MUST"
quote = '''
If the Encrypt call succeeds The response's "KeyId" MUST be A valid
AWS KMS key ARN (aws-kms-key-arn.md#identifying-an-aws-kms-multi-
region-key).
'''

[[spec]]
level = "MUST"
quote = '''
If verified, OnEncrypt MUST do the following with the
response from AWS KMS Encrypt
(https://docs.aws.amazon.com/kms/latest/APIReference/
API_Encrypt.html):
'''

[[spec]]
level = "MUST"
quote = '''
If all Encrypt calls succeed, OnEncrypt MUST output the modified
encryption materials (structures.md#encryption-materials).
'''

