target = "compliance/framework/master-key-interface.txt#2.5.5"

# 2.5.5.  Encrypt Data Key
#
# This interface is used to encrypt a data key.
# 
# The master key MUST encrypt the data key.
# 
# Inputs to this interface MUST include the algorithm suite, the
# encryption context, the encrypted data key, and information that can
# identify which master key was used to encrypt the data key.
# 
# The output of this interface MUST include a value that this master
# key can use to obtain the plaintext data key.  Most commonly, this
# will be the result of an encryption operation.
# 
# If the master key cannot encrypt the data key, the call MUST result
# in an error.

[[spec]]
level = "MUST"
quote = '''
The master key MUST encrypt the data key.
'''

[[spec]]
level = "MUST"
quote = '''
Inputs to this interface MUST include the algorithm suite, the
encryption context, the encrypted data key, and information that can
identify which master key was used to encrypt the data key.
'''

[[spec]]
level = "MUST"
quote = '''
The output of this interface MUST include a value that this master
key can use to obtain the plaintext data key.
'''

[[spec]]
level = "MUST"
quote = '''
If the master key cannot encrypt the data key, the call MUST result
in an error.
'''

