target = "compliance/framework/master-key-interface.txt#2.5.3"

# 2.5.3.  Decrypt Data Key
#
# Inputs and outputs are the same as for master key providers
# (./master-key-provider-interface.md).
# 
# A master key SHOULD attempt to decrypt a data key using itself.
# 
# A master key MUST not attempt to use any other master keys.

[[spec]]
level = "SHOULD"
quote = '''
A master key SHOULD attempt to decrypt a data key using itself.
'''

[[spec]]
level = "MUST"
quote = '''
A master key MUST not attempt to use any other master keys.
'''

