target = "compliance/framework/master-key-interface.txt#2.5.1"

# 2.5.1.  Get Master Key
#
# Inputs and outputs are the same as for master key providers
# (./master-key-provider-interface.md).
# 
# A master key MUST supply itself and MUST NOT supply any other master
# keys.

[[spec]]
level = "MUST"
quote = '''
A master key MUST supply itself and MUST NOT supply any other master
keys.
'''

[[spec]]
level = "MUST"
quote = '''
A master key MUST supply itself and MUST NOT supply any other master
keys.
'''

