target = "compliance/framework/master-key-interface.txt#2.5.4"

# 2.5.4.  Generate Data Key
#
# This interface is used to generate and encrypt a data key.
# 
# The master key MUST generate a data key and MUST then encrypt that
# data key.
# 
# Inputs to this interface MUST include the algorithm suite and the
# encryption context.
# 
# The output of this interface MUST include the plaintext data key, the
# data key encrypted under the master key, and information that can
# identify which master key was used to generate and encrypt the data
# key.
# 
# If the master key cannot generate or encrypt the data key, the call
# MUST result in an error.

[[spec]]
level = "MUST"
quote = '''
The master key MUST generate a data key and MUST then encrypt that
data key.
'''

[[spec]]
level = "MUST"
quote = '''
The master key MUST generate a data key and MUST then encrypt that
data key.
'''

[[spec]]
level = "MUST"
quote = '''
Inputs to this interface MUST include the algorithm suite and the
encryption context.
'''

[[spec]]
level = "MUST"
quote = '''
The output of this interface MUST include the plaintext data key, the
data key encrypted under the master key, and information that can
identify which master key was used to generate and encrypt the data
key.
'''

[[spec]]
level = "MUST"
quote = '''
If the master key cannot generate or encrypt the data key, the call
MUST result in an error.
'''

