target = "compliance/framework/aws-kms/aws-kms-mrk-aware-master-key.txt#2.10"

# 2.10.  Generate Data Key
#
# The inputs MUST be the same as the Master Key Generate Data Key
# (../master-key-interface.md#generate-data-key) interface.  This
# master key MUST use the configured AWS KMS client to make an AWS KMS
# GenerateDatakey (https://docs.aws.amazon.com/kms/latest/APIReference/
# API_GenerateDataKey.html) request constructed as follows:
# 
# *  "KeyId": The configured AWS KMS key identifier.
# 
# *  "NumberOfBytes": The key derivation input length specified by the
#    algorithm suite included in the input.
# 
# *  "EncryptionContext": The encryption context included in the input.
# 
# *  "GrantTokens": The configured grant tokens.
# 
# If the call succeeds the AWS KMS Generate Data Key response's
# "Plaintext" MUST match the key derivation input length specified by
# the algorithm suite included in the input.  The response's "KeyId"
# MUST be valid.  The response's "Plaintext" MUST be the plaintext in
# the output.  The response's cipher text blob MUST be used as the
# returned as the ciphertext for the encrypted data key in the output.
# 
# The output MUST be the same as the Master Key Generate Data Key
# (../master-key-interface.md#generate-data-key) interface.

[[spec]]
level = "MUST"
quote = '''
The inputs MUST be the same as the Master Key Generate Data Key
(../master-key-interface.md#generate-data-key) interface.
'''

[[spec]]
level = "MUST"
quote = '''
This
master key MUST use the configured AWS KMS client to make an AWS KMS
GenerateDatakey (https://docs.aws.amazon.com/kms/latest/APIReference/
API_GenerateDataKey.html) request constructed as follows:
'''

[[spec]]
level = "MUST"
quote = '''
If the call succeeds the AWS KMS Generate Data Key response's
"Plaintext" MUST match the key derivation input length specified by
the algorithm suite included in the input.
'''

[[spec]]
level = "MUST"
quote = '''
The response's "KeyId"
MUST be valid.
'''

[[spec]]
level = "MUST"
quote = '''
The response's "Plaintext" MUST be the plaintext in
the output.
'''

[[spec]]
level = "MUST"
quote = '''
The response's cipher text blob MUST be used as the
returned as the ciphertext for the encrypted data key in the output.
'''

[[spec]]
level = "MUST"
quote = '''
The output MUST be the same as the Master Key Generate Data Key
(../master-key-interface.md#generate-data-key) interface.
'''

