target = "compliance/framework/aws-kms/aws-kms-mrk-aware-master-key.txt#2.5"

# 2.5.  Interface
#
# MUST implement the Master Key Interface (../master-key-
# interface.md#interface)

[[spec]]
level = "MUST"
quote = '''
MUST implement the Master Key Interface (../master-key-
interface.md#interface)
'''

