target = "compliance/framework/aws-kms/aws-kms-mrk-aware-master-key.txt#2.6"

# 2.6.  Initialization
#
# On initialization, the caller MUST provide:
# 
# *  An AWS KMS key identifier
# 
# *  An AWS KMS SDK client.
# 
# The AWS KMS key identifier MUST NOT be null or empty.  The AWS KMS
# key identifier MUST be a valid identifier (aws-kms-key-arn.md#a-
# valid-aws-kms-identifier).  The AWS KMS SDK client MUST not be null.
# The master key MUST be able to be configured with an optional list of
# Grant Tokens.  This configuration SHOULD be on initialization and
# SHOULD be immutable.

[[spec]]
level = "MUST"
quote = '''
On initialization, the caller MUST provide:
'''

[[spec]]
level = "MUST"
quote = '''
The AWS KMS key identifier MUST NOT be null or empty.
'''

[[spec]]
level = "MUST"
quote = '''
The AWS KMS
key identifier MUST be a valid identifier (aws-kms-key-arn.md#a-
valid-aws-kms-identifier).
'''

[[spec]]
level = "MUST"
quote = '''
The AWS KMS SDK client MUST not be null.
'''

[[spec]]
level = "MUST"
quote = '''
The master key MUST be able to be configured with an optional list of
Grant Tokens.
'''

[[spec]]
level = "SHOULD"
quote = '''
This configuration SHOULD be on initialization and
SHOULD be immutable.
'''

[[spec]]
level = "SHOULD"
quote = '''
This configuration SHOULD be on initialization and
SHOULD be immutable.
'''

