target = "compliance/framework/aws-kms/aws-kms-mrk-aware-master-key.txt#2.8"

# 2.8.  Get Master Keys For Encryption
#
# MUST be unchanged from the Master Key interface.

[[spec]]
level = "MUST"
quote = '''
MUST be unchanged from the Master Key interface.
'''

