target = "compliance/framework/aws-kms/aws-kms-mrk-aware-master-key.txt#2.9"

# 2.9.  Decrypt Data Key
#
# The inputs MUST be the same as the Master Key Decrypt Data Key
# (../master-key-interface.md#decrypt-data-key) interface.
# 
# The set of encrypted data keys MUST first be filtered to match this
# master key's configuration.  To match the encrypted data key's
# provider ID MUST exactly match the value "aws-kms" and the the
# function AWS KMS MRK Match for Decrypt (aws-kms-mrk-match-for-
# decrypt.md#implementation) called with the configured AWS KMS key
# identifier and the encrypted data key's provider info MUST return
# "true".  Additionally each provider info MUST be a valid AWS KMS ARN
# (aws-kms-key-arn.md#a-valid-aws-kms-arn) with a resource type of
# "key".
# 
# For each encrypted data key in the filtered set, one at a time, the
# master key MUST attempt to decrypt the data key.  If this attempt
# results in an error, then these errors MUST be collected.
# 
# To decrypt the encrypted data key this master key MUST use the
# configured AWS KMS client to make an AWS KMS Decrypt
# (https://docs.aws.amazon.com/kms/latest/APIReference/
# API_Decrypt.html) request constructed as follows:
# 
# *  "KeyId": The configured AWS KMS key identifier.
# 
# *  "CiphertextBlob": The "ciphertext" from the encrypted data key.
# 
# *  "EncryptionContext": The encryption context included in the input.
# 
# *  "GrantTokens": The configured grant tokens.
# 
# If the call succeeds then the response's "KeyId" MUST be equal to the
# configured AWS KMS key identifier otherwise the function MUST collect
# an error.  The response's "Plaintext"'s length MUST equal the length
# required by the requested algorithm suite otherwise the function MUST
# collect an error.
# 
# If the AWS KMS response satisfies the requirements then it MUST be
# use and this function MUST return and not attempt to decrypt any more
# encrypted data keys.
# 
# If all the input encrypted data keys have been processed then this
# function MUST yield an error that includes all the collected errors.
# 
# The output MUST be the same as the Master Key Decrypt Data Key
# (../master-key-interface.md#decrypt-data-key) interface.

[[spec]]
level = "MUST"
quote = '''
The inputs MUST be the same as the Master Key Decrypt Data Key
(../master-key-interface.md#decrypt-data-key) interface.
'''

[[spec]]
level = "MUST"
quote = '''
The set of encrypted data keys MUST first be filtered to match this
master key's configuration.
'''

[[spec]]
level = "MUST"
quote = '''
To match the encrypted data key's
provider ID MUST exactly match the value "aws-kms" and the the
function AWS KMS MRK Match for Decrypt (aws-kms-mrk-match-for-
decrypt.md#implementation) called with the configured AWS KMS key
identifier and the encrypted data key's provider info MUST return
"true".
'''

[[spec]]
level = "MUST"
quote = '''
To match the encrypted data key's
provider ID MUST exactly match the value "aws-kms" and the the
function AWS KMS MRK Match for Decrypt (aws-kms-mrk-match-for-
decrypt.md#implementation) called with the configured AWS KMS key
identifier and the encrypted data key's provider info MUST return
"true".
'''

[[spec]]
level = "MUST"
quote = '''
Additionally each provider info MUST be a valid AWS KMS ARN
(aws-kms-key-arn.md#a-valid-aws-kms-arn) with a resource type of
"key".
'''

[[spec]]
level = "MUST"
quote = '''
For each encrypted data key in the filtered set, one at a time, the
master key MUST attempt to decrypt the data key.
'''

[[spec]]
level = "MUST"
quote = '''
If this attempt
results in an error, then these errors MUST be collected.
'''

[[spec]]
level = "MUST"
quote = '''
To decrypt the encrypted data key this master key MUST use the
configured AWS KMS client to make an AWS KMS Decrypt
(https://docs.aws.amazon.com/kms/latest/APIReference/
API_Decrypt.html) request constructed as follows:
'''

[[spec]]
level = "MUST"
quote = '''
If the call succeeds then the response's "KeyId" MUST be equal to the
configured AWS KMS key identifier otherwise the function MUST collect
an error.
'''

[[spec]]
level = "MUST"
quote = '''
If the call succeeds then the response's "KeyId" MUST be equal to the
configured AWS KMS key identifier otherwise the function MUST collect
an error.
'''

[[spec]]
level = "MUST"
quote = '''
The response's "Plaintext"'s length MUST equal the length
required by the requested algorithm suite otherwise the function MUST
collect an error.
'''

[[spec]]
level = "MUST"
quote = '''
The response's "Plaintext"'s length MUST equal the length
required by the requested algorithm suite otherwise the function MUST
collect an error.
'''

[[spec]]
level = "MUST"
quote = '''
If the AWS KMS response satisfies the requirements then it MUST be
use and this function MUST return and not attempt to decrypt any more
encrypted data keys.
'''

[[spec]]
level = "MUST"
quote = '''
If the AWS KMS response satisfies the requirements then it MUST be
use and this function MUST return and not attempt to decrypt any more
encrypted data keys.
'''

[[spec]]
level = "MUST"
quote = '''
If all the input encrypted data keys have been processed then this
function MUST yield an error that includes all the collected errors.
'''

[[spec]]
level = "MUST"
quote = '''
The output MUST be the same as the Master Key Decrypt Data Key
(../master-key-interface.md#decrypt-data-key) interface.
'''

