target = "compliance/framework/kms-keyring.txt#2.5.1"

# 2.5.1.  Client Supplier
#
# In order to communicate with AWS KMS, the AWS KMS keyring requires an
# AWS SDK client.  The role of the client supplier is to create and
# configure those clients and supply them to the AWS KMS keyring.
# 
# A function that MUST take as input either a region string (e.g. "us-
# east-1"), or some value denoting an unknown region, and MAY return an
# AWS KMS Client that can make the following API calls in the given AWS
# region:
# 
# *  GenerateDataKey (Section 2.4.2)
# 
# *  Encrypt (Section 2.4.3)
# 
# *  Decrypt (Section 2.4.4)
# 
# If the client supplier cannot supply a client for the requested
# region, it MUST communicate that fact to the AWS KMS keyring.

[[spec]]
level = "MUST"
quote = '''
A function that MUST take as input either a region string (e.g.
'''

[[spec]]
level = "MAY"
quote = '''
"us-
east-1"), or some value denoting an unknown region, and MAY return an
AWS KMS Client that can make the following API calls in the given AWS
region:
'''

[[spec]]
level = "MUST"
quote = '''
If the client supplier cannot supply a client for the requested
region, it MUST communicate that fact to the AWS KMS keyring.
'''

