target = "compliance/framework/kms-keyring.txt#2.5"

# 2.5.  Initialization
#
# On keyring initialization, the caller MUST provide the following:
# 
# *  Client Supplier (Section 2.5.1)
# 
# On keyring initialization, the keyring MUST optionally accept the
# following:
# 
# *  Key Names (Section 2.5.2)
# 
# *  Section 2.5.3
# 
# *  Grant Tokens (Section 2.5.4)

[[spec]]
level = "MUST"
quote = '''
On keyring initialization, the caller MUST provide the following:
'''

[[spec]]
level = "MUST"
quote = '''
On keyring initialization, the keyring MUST optionally accept the
following:
'''

