target = "compliance/framework/kms-keyring.txt#2.6.1"

# 2.6.1.  Is Discovery
#
# Indicates whether this keyring is a discovery keyring.  Discovery
# keyrings do not perform encryption and on decryption attempt to
# decrypt any encrypted data key (structures.md#encrypted-data-key)
# that was encrypted by the AWS KMS keyring, if the client supplier
# returns a client.
# 
# If this keyring has defined a Section 2.5.3 or key names
# (Section 2.5.2), this value MUST be false.  Otherwise, this value
# MUST be true.
# 
# If this value is true, the keyring MUST only ever call AWS KMS
# Decrypt (Section 2.4.4).

[[spec]]
level = "MUST"
quote = '''
If this keyring has defined a Section 2.5.3 or key names
(Section 2.5.2), this value MUST be false.
'''

[[spec]]
level = "MUST"
quote = '''
Otherwise, this value
MUST be true.
'''

[[spec]]
level = "MUST"
quote = '''
If this value is true, the keyring MUST only ever call AWS KMS
Decrypt (Section 2.4.4).
'''

