target = "compliance/framework/kms-keyring.txt#2.7.1"

# 2.7.1.  OnEncrypt
#
# OnEncrypt MUST take encryption materials (structures.md#encryption-
# materials) as input.
# 
# If this keyring is a discovery keyring (Section 2.6.1), OnEncrypt
# MUST return the input encryption materials (structures.md#encryption-
# materials) unmodified.
# 
# If the input encryption materials (structures.md#encryption-
# materials) do not contain a plaintext data key and this keyring does
# not have a Section 2.5.3 defined, OnEncrypt MUST not modify the
# encryption materials (structures.md#encryption-materials) and MUST
# fail.
# 
# If the input encryption materials (structures.md#encryption-
# materials) do not contain a plaintext data key and this keyring has a
# Section 2.5.3 defined, and OnEncrypt MUST attempt to generate a new
# plaintext data key and encrypt that data key by calling AWS KMS
# GenerateDataKey (Section 2.4.2).
# 
# If an AWS region can be extracted from the Section 2.5.3, then the
# AWS KMS client (Section 2.4.1.1) that calls AWS KMS GenerateDataKey
# (Section 2.4.2) MUST be the client returned by the client supplier
# (Section 2.5.1) when given that region as input.  If an AWS region
# cannot be extracted from the Section 2.5.3 then the AWS KMS Keyring
# MUST input a value denoting an unknown region.  If the client
# supplier (Section 2.5.1) does not provide any client for the given
# region for this AWS KMS GenerateDataKey (Section 2.4.2) call,
# OnEncrypt MUST NOT modify the encryption materials
# (structures.md#encryption-materials) and MUST fail.
# 
# When calling AWS KMS GenerateDataKey (Section 2.4.2), the keyring
# MUST call with a request constructed as follows:
# 
# *  "KeyId": this keyring's Section 2.5.3.
# 
# *  "NumberOfBytes": the key derivation input length (algorithm-
#    suites.md#key-derivation-input-length) specified by the algorithm
#    suite (algorithm-suites.md) included in the input encryption
#    materials (structures.md#encryption-materials).
# 
# *  "EncryptionContext": the encryption context
#    (structures.md#encryption-context) included in the input
#    encryption materials (structures.md#encryption-materials).
# 
# *  "GrantTokens": this keyring's grant tokens (Section 2.5.4)
# 
# If the call to AWS KMS GenerateDataKey (Section 2.4.2) does not
# succeed, OnEncrypt MUST NOT modify the encryption materials
# (structures.md#encryption-materials) and MUST fail.
# 
# If the call succeeds, OnEncrypt MUST verify that the response
# "Plaintext" length matches the specification of the algorithm suite
# (algorithm-suites.md)'s Key Derivation Input Length field.  If it
# does not, OnEncrypt MUST fail.  If verified, OnEncrypt MUST do the
# following with the response from AWS KMS GenerateDataKey
# (Section 2.4.2):
# 
# *  set the plaintext data key on the encryption materials
#    (structures.md#encryption-materials) as the response "Plaintext".
# 
# *  append a new encrypted data key (structures.md#encrypted-data-key)
#    to the encrypted data key list in the encryption materials
#    (structures.md#encryption-materials), constructed as follows:
# 
#    -  the ciphertext (structures.md#ciphertext) is the response
#       "CiphertextBlob".
# 
#    -  the key provider id (structures.md#key-provider-id) is "aws-
#       kms".
# 
#    -  the key provider information (structures.md#key-provider-
#       information) is the response "KeyId".  Given a plaintext data
#       key in the encryption materials (structures.md#encryption-
#       materials), OnEncrypt MUST attempt to encrypt the plaintext
#       data key using each CMK specified in its key names
#       (Section 2.5.2) list.
# 
# If this keyring's Section 2.5.3 is defined and was not used to
# generate a data key (Section 2.4.2) as described above, OnEncrypt
# MUST also attempt to encrypt the plaintext data key using the CMK
# specified by the Section 2.5.3.
# 
# To attempt to encrypt the plaintext data key with a particular CMK,
# OnEncrypt MUST call AWS KMS Encrypt (Section 2.4.3).
# 
# For each AWS KMS Encrypt (Section 2.4.3) call, if an AWS region can
# be extracted from the key name (Section 2.5.2), then the AWS KMS
# client (Section 2.4.1.1) that calls AWS KMS Encrypt (Section 2.4.3)
# MUST be the client returned by the client supplier (Section 2.5.1)
# when given that region as input.  If an AWS region cannot be
# extracted from the key name then the AWS KMS Keyring MUST input a
# value denoting an unknown region.  If the client supplier
# (Section 2.5.1) does not provide any client for the given region for
# this AWS KMS Encrypt (Section 2.4.3) call, OnEncrypt MUST NOT modify
# the encryption materials (structures.md#encryption-materials) and
# MUST fail.
# 
# To encrypt the plaintext data key with a CMK, OnEncrypt MUST call AWS
# KMS Encrypt (Section 2.4.3) with a request constructed as follows:
# 
# *  "KeyId": the CMK ARN to be used for data key encryption.
# 
# *  "PlaintextDataKey": the plaintext data key in the encryption
#    materials (structures.md#encryption-materials).
# 
# *  "EncryptionContext": the encryption context
#    (structures.md#encryption-context) included in the input
#    encryption materials (structures.md#encryption-materials).
# 
# *  "GrantTokens": this keyring's grant tokens (Section 2.5.4)
# 
# If the call to AWS KMS Encrypt (Section 2.4.3) does not succeed,
# OnEncrypt MUST fail.
# 
# If the call succeeds, OnEncrypt MUST do the following with the
# response from AWS KMS Encrypt (Section 2.4.3):
# 
# *  append a new encrypted data key (structures.md#encrypted-data-key)
#    to the encrypted data key list in the encryption materials
#    (structures.md#encryption-materials), constructed as follows:
# 
#    -  The ciphertext (structures.md#ciphertext) is the response
#       "CiphertextBlob".
# 
#    -  The key provider id (structures.md#key-provider-id) is "aws-
#       kms".
# 
#    -  The key provider information (structures.md#key-provider-
#       information) is the response "KeyId".  Note that the "KeyId" in
#       the response is always in key ARN format.
# 
# If all Encrypt calls succeed, OnEncrypt MUST output the modified
# encryption materials (structures.md#encryption-materials).

[[spec]]
level = "MUST"
quote = '''
OnEncrypt MUST take encryption materials (structures.md#encryption-
materials) as input.
'''

[[spec]]
level = "MUST"
quote = '''
If this keyring is a discovery keyring (Section 2.6.1), OnEncrypt
MUST return the input encryption materials (structures.md#encryption-
materials) unmodified.
'''

[[spec]]
level = "MUST"
quote = '''
If the input encryption materials (structures.md#encryption-
materials) do not contain a plaintext data key and this keyring does
not have a Section 2.5.3 defined, OnEncrypt MUST not modify the
encryption materials (structures.md#encryption-materials) and MUST
fail.
'''

[[spec]]
level = "MUST"
quote = '''
If the input encryption materials (structures.md#encryption-
materials) do not contain a plaintext data key and this keyring does
not have a Section 2.5.3 defined, OnEncrypt MUST not modify the
encryption materials (structures.md#encryption-materials) and MUST
fail.
'''

[[spec]]
level = "MUST"
quote = '''
If the input encryption materials (structures.md#encryption-
materials) do not contain a plaintext data key and this keyring has a
Section 2.5.3 defined, and OnEncrypt MUST attempt to generate a new
plaintext data key and encrypt that data key by calling AWS KMS
GenerateDataKey (Section 2.4.2).
'''

[[spec]]
level = "MUST"
quote = '''
If an AWS region can be extracted from the Section 2.5.3, then the
AWS KMS client (Section 2.4.1.1) that calls AWS KMS GenerateDataKey
(Section 2.4.2) MUST be the client returned by the client supplier
(Section 2.5.1) when given that region as input.
'''

[[spec]]
level = "MUST"
quote = '''
If an AWS region
cannot be extracted from the Section 2.5.3 then the AWS KMS Keyring
MUST input a value denoting an unknown region.
'''

[[spec]]
level = "MUST"
quote = '''
If the client
supplier (Section 2.5.1) does not provide any client for the given
region for this AWS KMS GenerateDataKey (Section 2.4.2) call,
OnEncrypt MUST NOT modify the encryption materials
(structures.md#encryption-materials) and MUST fail.
'''

[[spec]]
level = "MUST"
quote = '''
If the client
supplier (Section 2.5.1) does not provide any client for the given
region for this AWS KMS GenerateDataKey (Section 2.4.2) call,
OnEncrypt MUST NOT modify the encryption materials
(structures.md#encryption-materials) and MUST fail.
'''

[[spec]]
level = "MUST"
quote = '''
When calling AWS KMS GenerateDataKey (Section 2.4.2), the keyring
MUST call with a request constructed as follows:
'''

[[spec]]
level = "MUST"
quote = '''
If the call to AWS KMS GenerateDataKey (Section 2.4.2) does not
succeed, OnEncrypt MUST NOT modify the encryption materials
(structures.md#encryption-materials) and MUST fail.
'''

[[spec]]
level = "MUST"
quote = '''
If the call to AWS KMS GenerateDataKey (Section 2.4.2) does not
succeed, OnEncrypt MUST NOT modify the encryption materials
(structures.md#encryption-materials) and MUST fail.
'''

[[spec]]
level = "MUST"
quote = '''
If the call succeeds, OnEncrypt MUST verify that the response
"Plaintext" length matches the specification of the algorithm suite
(algorithm-suites.md)'s Key Derivation Input Length field.
'''

[[spec]]
level = "MUST"
quote = '''
If it
does not, OnEncrypt MUST fail.
'''

[[spec]]
level = "MUST"
quote = '''
If verified, OnEncrypt MUST do the
following with the response from AWS KMS GenerateDataKey
(Section 2.4.2):
'''

[[spec]]
level = "MUST"
quote = '''
Given a plaintext data
key in the encryption materials (structures.md#encryption-
materials), OnEncrypt MUST attempt to encrypt the plaintext
data key using each CMK specified in its key names
(Section 2.5.2) list.
'''

[[spec]]
level = "MUST"
quote = '''
If this keyring's Section 2.5.3 is defined and was not used to
generate a data key (Section 2.4.2) as described above, OnEncrypt
MUST also attempt to encrypt the plaintext data key using the CMK
specified by the Section 2.5.3.
'''

[[spec]]
level = "MUST"
quote = '''
To attempt to encrypt the plaintext data key with a particular CMK,
OnEncrypt MUST call AWS KMS Encrypt (Section 2.4.3).
'''

[[spec]]
level = "MUST"
quote = '''
For each AWS KMS Encrypt (Section 2.4.3) call, if an AWS region can
be extracted from the key name (Section 2.5.2), then the AWS KMS
client (Section 2.4.1.1) that calls AWS KMS Encrypt (Section 2.4.3)
MUST be the client returned by the client supplier (Section 2.5.1)
when given that region as input.
'''

[[spec]]
level = "MUST"
quote = '''
If an AWS region cannot be
extracted from the key name then the AWS KMS Keyring MUST input a
value denoting an unknown region.
'''

[[spec]]
level = "MUST"
quote = '''
If the client supplier
(Section 2.5.1) does not provide any client for the given region for
this AWS KMS Encrypt (Section 2.4.3) call, OnEncrypt MUST NOT modify
the encryption materials (structures.md#encryption-materials) and
MUST fail.
'''

[[spec]]
level = "MUST"
quote = '''
If the client supplier
(Section 2.5.1) does not provide any client for the given region for
this AWS KMS Encrypt (Section 2.4.3) call, OnEncrypt MUST NOT modify
the encryption materials (structures.md#encryption-materials) and
MUST fail.
'''

[[spec]]
level = "MUST"
quote = '''
To encrypt the plaintext data key with a CMK, OnEncrypt MUST call AWS
KMS Encrypt (Section 2.4.3) with a request constructed as follows:
'''

[[spec]]
level = "MUST"
quote = '''
If the call to AWS KMS Encrypt (Section 2.4.3) does not succeed,
OnEncrypt MUST fail.
'''

[[spec]]
level = "MUST"
quote = '''
If the call succeeds, OnEncrypt MUST do the following with the
response from AWS KMS Encrypt (Section 2.4.3):
'''

[[spec]]
level = "MUST"
quote = '''
If all Encrypt calls succeed, OnEncrypt MUST output the modified
encryption materials (structures.md#encryption-materials).
'''

