target = "compliance/framework/kms-keyring.txt#2.8.4"

# 2.8.4.  Requirements
#
# These goals can be reduced to the following two requirements:
# 
# 1.  On encrypt, if any configured CMK cannot be used, that is an
#     error and encryption MUST halt.
# 
# 2.  On decrypt, the keyring MUST NOT halt decryption because of a
#     failure to decrypt.

[[spec]]
level = "MUST"
quote = '''
On encrypt, if any configured CMK cannot be used, that is an
error and encryption MUST halt.
'''

[[spec]]
level = "MUST"
quote = '''
On decrypt, the keyring MUST NOT halt decryption because of a
failure to decrypt.
'''

