target = "compliance/framework/multi-keyring.txt#2.6.2"

# 2.6.2.  Child Keyrings
#
# A list of keyrings (keyring-interface.md) to be used to modify the
# encryption (structures.md#encryption-materials) or decryption
# materials (structures.md#decryption-materials).
# 
# If this keyring does not have a generator keyring (Section 2.6.1),
# this list MUST NOT be empty.

[[spec]]
level = "MUST"
quote = '''
If this keyring does not have a generator keyring (Section 2.6.1),
this list MUST NOT be empty.
'''

