target = "compliance/framework/multi-keyring.txt#2.6"

# 2.6.  Inputs
#
# On keyring initialization, a keyring MUST define at least one of the
# following:
# 
# *  Generator Keyring (Section 2.6.1)
# 
# *  Child Keyrings (Section 2.6.2)

[[spec]]
level = "MUST"
quote = '''
On keyring initialization, a keyring MUST define at least one of the
following:
'''

