target = "compliance/framework/multi-keyring.txt#2.7.2"

# 2.7.2.  OnDecrypt
#
# If the decryption materials already contain a plaintext data key, the
# keyring MUST fail and MUST NOT modify the decryption materials
# (structures.md#decryption-materials).
# 
# Otherwise, OnDecrypt MUST attempt to decrypt the encrypted data keys
# (structures.md#encrypted-data-keys-1) in the input decryption
# materials (structures.md#decryption-materials) using its child
# keyrings (Section 2.6.2) and, if it is specified, its generator
# keyring (Section 2.6.1).  It MUST attempt to decrypt using these
# keyrings until it either succeeds in decryption, or it has attempted
# to decrypt using all its child keyrings and, if it is specified, its
# generator keyring.  If a generator keyring is specified, it MUST be
# used first.
# 
# For each keyring (keyring-interface.md) to be used for decryption,
# the multi-keyring MUST call that keyring's OnDecrypt (keyring-
# interface.md#ondecrypt) using the unmodified decryption materials
# (structures.md#decryption-materials) and the input encrypted data key
# (structures.md#encrypted-data-key) list.  If OnDecrypt (keyring-
# interface.md#ondecrypt) returns decryption materials
# (structures.md#decryption-materials) containing a plaintext data key,
# the keyring MUST immediately return the modified decryption
# materials.
# 
# If, after calling OnDecrypt (keyring-interface.md#ondecrypt) on every
# child keyring (Section 2.6.2) (and possibly the generator keyring
# (Section 2.6.1)), the decryption materials (structures.md#decryption-
# materials) still do not contain a plaintext data key:
# 
# *  If none of the above OnDecrypt (keyring-interface.md#ondecrypt)
#    calls failed, the keyring MUST return the unmodified decryption
#    materials (structures.md#decryption-materials).
# 
# *  If at least one of the above OnDecrypt (keyring-
#    interface.md#ondecrypt) calls failed, OnDecrypt MUST also fail,
#    and MUST not modify the input decryption materials
#    (structures.md#decryption-materials).

[[spec]]
level = "MUST"
quote = '''
If the decryption materials already contain a plaintext data key, the
keyring MUST fail and MUST NOT modify the decryption materials
(structures.md#decryption-materials).
'''

[[spec]]
level = "MUST"
quote = '''
If the decryption materials already contain a plaintext data key, the
keyring MUST fail and MUST NOT modify the decryption materials
(structures.md#decryption-materials).
'''

[[spec]]
level = "MUST"
quote = '''
Otherwise, OnDecrypt MUST attempt to decrypt the encrypted data keys
(structures.md#encrypted-data-keys-1) in the input decryption
materials (structures.md#decryption-materials) using its child
keyrings (Section 2.6.2) and, if it is specified, its generator
keyring (Section 2.6.1).
'''

[[spec]]
level = "MUST"
quote = '''
It MUST attempt to decrypt using these
keyrings until it either succeeds in decryption, or it has attempted
to decrypt using all its child keyrings and, if it is specified, its
generator keyring.
'''

[[spec]]
level = "MUST"
quote = '''
If a generator keyring is specified, it MUST be
used first.
'''

[[spec]]
level = "MUST"
quote = '''
For each keyring (keyring-interface.md) to be used for decryption,
the multi-keyring MUST call that keyring's OnDecrypt (keyring-
interface.md#ondecrypt) using the unmodified decryption materials
(structures.md#decryption-materials) and the input encrypted data key
(structures.md#encrypted-data-key) list.
'''

[[spec]]
level = "MUST"
quote = '''
If OnDecrypt (keyring-
interface.md#ondecrypt) returns decryption materials
(structures.md#decryption-materials) containing a plaintext data key,
the keyring MUST immediately return the modified decryption
materials.
'''

[[spec]]
level = "MUST"
quote = '''
*  If none of the above OnDecrypt (keyring-interface.md#ondecrypt)
calls failed, the keyring MUST return the unmodified decryption
materials (structures.md#decryption-materials).
'''

[[spec]]
level = "MUST"
quote = '''
*  If at least one of the above OnDecrypt (keyring-
interface.md#ondecrypt) calls failed, OnDecrypt MUST also fail,
and MUST not modify the input decryption materials
(structures.md#decryption-materials).
'''

[[spec]]
level = "MUST"
quote = '''
*  If at least one of the above OnDecrypt (keyring-
interface.md#ondecrypt) calls failed, OnDecrypt MUST also fail,
and MUST not modify the input decryption materials
(structures.md#decryption-materials).
'''

