target = "compliance/framework/multi-keyring.txt#2.7.1"

# 2.7.1.  OnEncrypt
#
# If this keyring has a generator keyring, this keyring MUST first
# generate a plaintext data key using the generator keyring:
# 
# *  If the input encryption materials already include a plaintext data
#    key, OnEncrypt MUST fail.
# 
# *  This keyring MUST first call the generator keyring's OnEncrypt
#    using the input encryption materials as input.
# 
# *  If the generator keyring fails OnEncrypt, this OnEncrypt MUST also
#    fail.
# 
# *  If the generator keyring returns encryption materials missing a
#    plaintext data key, OnEncrypt MUST fail.
# 
# If this keyring does not have a generator keyring (Section 2.6.1),
# and the input encryption materials (structures.md#encryption-
# materials) does not include a plaintext data key, OnEncrypt MUST
# fail.
# 
# Next, for each keyring (keyring-interface.md) in this keyring's list
# of child keyrings (Section 2.6.2), the keyring MUST call OnEncrypt
# (keyring-interface.md#onencrypt).  The encryption materials
# (structures.md#encryption-materials) input into OnEncrypt are the
# input encryption materials if this is the first OnEncrypt call.  If
# this is not the first OnEncrypt call, the encryption materials input
# into OnEncrypt are the encryption materials output by the previous
# OnEncrypt call.  If the child keyring's OnEncrypt (keyring-
# interface.md#onencrypt) fails, this OnEncrypt MUST also fail.
# 
# If all previous OnEncrypt (keyring-interface.md#onencrypt) calls
# succeeded, this keyring MUST return the encryption materials
# (structures.md#encryption-materials) returned by the last OnEncrypt
# call.

[[spec]]
level = "MUST"
quote = '''
If this keyring has a generator keyring, this keyring MUST first
generate a plaintext data key using the generator keyring:
'''

[[spec]]
level = "MUST"
quote = '''
*  If the input encryption materials already include a plaintext data
key, OnEncrypt MUST fail.
'''

[[spec]]
level = "MUST"
quote = '''
*  This keyring MUST first call the generator keyring's OnEncrypt
using the input encryption materials as input.
'''

[[spec]]
level = "MUST"
quote = '''
*  If the generator keyring fails OnEncrypt, this OnEncrypt MUST also
fail.
'''

[[spec]]
level = "MUST"
quote = '''
*  If the generator keyring returns encryption materials missing a
plaintext data key, OnEncrypt MUST fail.
'''

[[spec]]
level = "MUST"
quote = '''
If this keyring does not have a generator keyring (Section 2.6.1),
and the input encryption materials (structures.md#encryption-
materials) does not include a plaintext data key, OnEncrypt MUST
fail.
'''

[[spec]]
level = "MUST"
quote = '''
Next, for each keyring (keyring-interface.md) in this keyring's list
of child keyrings (Section 2.6.2), the keyring MUST call OnEncrypt
(keyring-interface.md#onencrypt).
'''

[[spec]]
level = "MUST"
quote = '''
If the child keyring's OnEncrypt (keyring-
interface.md#onencrypt) fails, this OnEncrypt MUST also fail.
'''

[[spec]]
level = "MUST"
quote = '''
If all previous OnEncrypt (keyring-interface.md#onencrypt) calls
succeeded, this keyring MUST return the encryption materials
(structures.md#encryption-materials) returned by the last OnEncrypt
call.
'''

