target = "compliance/framework/multi-keyring.txt#2.8"

# 2.8.  Security Considerations
#
# Users SHOULD examine the keyrings (keyring-interface.md) they include
# in a multi-keyring to ensure that they understand what set of
# keyrings will be capable of obtaining the plaintext data key from the
# returned set of encrypted data keys.
# 
# In more detail:
# 
# Multi-keyrings will produce a set of encrypted data keys
# (structures.md#encrypted-data-key) on OnEncrypt (keyring-
# interface.md#onencrypt) that includes the encrypted data keys of
# every sub-keyring (a keyring which is either the generator keyring
# (Section 2.6.1) or a member of child keyrings (Section 2.6.2)) that
# is capable of producing encrypted data keys.
# 
# As such, any keyring (keyring-interface.md) that is capable of
# obtaining the plaintext data key from encrypted data keys
# (structures.md#encrypted-data-key) produced by one of the sub-
# keyrings, by definition, is capable of obtaining the plaintext data
# key for the set of encrypted data keys the multi-keyring produces on
# OnEncrypt (keyring-interface.md#onencrypt).
# 
# In typical cases, most keyrings (keyring-interface.md) are defined
# such that they are capable of decrypting the encrypted data keys they
# produce.  As such, when including such keyrings (keyring-
# interface.md), the multi-keyring will produce a set of encrypted data
# keys (structures.md#encrypted-data-keys) such that any one of the
# sub-keyrings is capable of obtaining the plaintext data key.

[[spec]]
level = "SHOULD"
quote = '''
Users SHOULD examine the keyrings (keyring-interface.md) they include
in a multi-keyring to ensure that they understand what set of
keyrings will be capable of obtaining the plaintext data key from the
returned set of encrypted data keys.
'''

