target = "compliance/client-apis/encrypt.txt#2.4.5"

# 2.4.5.  Algorithm Suite
#
# The algorithm suite (../framework/algorithm-suite.md) that SHOULD be
# used for encryption.

[[spec]]
level = "SHOULD"
quote = '''
The algorithm suite (../framework/algorithm-suite.md) that SHOULD be
used for encryption.
'''

