target = "compliance/client-apis/encrypt.txt#2.4.1"

# 2.4.1.  Plaintext
#
# The plaintext to encrypt.  This MUST be a sequence of bytes.
# 
# This input MAY be streamed (streaming.md) to this operation.
# 
# If an implementation requires holding the input entire plaintext in
# memory in order to perform this operation, that implementation SHOULD
# NOT provide an API that allows this input to be streamed.

[[spec]]
level = "MUST"
quote = '''
This MUST be a sequence of bytes.
'''

[[spec]]
level = "MAY"
quote = '''
This input MAY be streamed (streaming.md) to this operation.
'''

[[spec]]
level = "SHOULD"
quote = '''
If an implementation requires holding the input entire plaintext in
memory in order to perform this operation, that implementation SHOULD
NOT provide an API that allows this input to be streamed.
'''

