target = "compliance/client-apis/encrypt.txt#2.5.1"

# 2.5.1.  Encrypted Message
#
# An encrypted form of the input Section 2.4.1, encrypted according to
# the behavior specified below (Section 2.6).  This MUST be a sequence
# of bytes and conform to the message format specification (../data-
# format/message.md).
# 
# This operation MAY stream (streaming.md) the encrypted message.
# 
# If an implementation requires holding the entire input plaintext in
# memory in order to perform this operation, that implementation SHOULD
# NOT provide an API that allows this output to be streamed.

[[spec]]
level = "MUST"
quote = '''
This MUST be a sequence
of bytes and conform to the message format specification (../data-
format/message.md).
'''

[[spec]]
level = "MAY"
quote = '''
This operation MAY stream (streaming.md) the encrypted message.
'''

[[spec]]
level = "SHOULD"
quote = '''
If an implementation requires holding the entire input plaintext in
memory in order to perform this operation, that implementation SHOULD
NOT provide an API that allows this output to be streamed.
'''

