target = "compliance/client-apis/encrypt.txt#2.5.3"

# 2.5.3.  Algorithm Suite
#
# The algorithm suite (../framework/algorithm-suites.md) that is used
# to encrypt the input Section 2.4.1.
# 
# This output MAY be satisfied by outputting a parsed header
# (Section 2.5.4) containing this value.

[[spec]]
level = "MAY"
quote = '''
This output MAY be satisfied by outputting a parsed header
(Section 2.5.4) containing this value.
'''

