target = "compliance/client-apis/encrypt.txt#2.5.2"

# 2.5.2.  Encryption Context
#
# The encryption context (../framework/structures.md#encryption-
# context) that is used as additional authenticated data during the
# encryption of the input Section 2.4.1.
# 
# This output MAY be satisfied by outputting a parsed header
# (Section 2.5.4) containing this value.

[[spec]]
level = "MAY"
quote = '''
This output MAY be satisfied by outputting a parsed header
(Section 2.5.4) containing this value.
'''

