target = "compliance/client-apis/encrypt.txt#2.6.2"

# 2.6.2.  Construct the header
#
# Before encrypting input plaintext, this operation MUST serialize the
# message header body (../data-format/message-header.md).  The message
# format version (../data-format/message-header.md#supported-versions)
# MUST be associated with the algorithm suite (../framework/algorithm-
# suites.md#supported-algorithm-suites).
# 
# If the message format version associated with the algorithm suite
# (../framework/algorithm-suites.md#supported-algorithm-suites) is 2.0
# then the message header body (../data-format/message-
# header.md#header-body-version-1-0) MUST be serialized with the
# following specifics:
# 
# *  Version (../data-format/message-header.md#version-1): MUST have a
#    value corresponding to 2.0 (../data-format/message-
#    header.md#supported-versions)
# 
# *  Algorithm Suite ID (../data-format/message-header.md#algorithm-
#    suite-id): MUST correspond to the algorithm suite (../framework/
#    algorithm-suites.md) used in this behavior
# 
# *  Message ID (../data-format/message-header.md#message-id): The
#    process used to generate this identifier MUST use a good source of
#    randomness to make the chance of duplicate identifiers negligible.
# 
# *  AAD (../data-format/message-header.md#aad): MUST be the
#    serialization of the encryption context (../framework/
#    structures.md#encryption-context) in the encryption materials
#    (../framework/structures.md#encryption-materials)
# 
# *  Encrypted Data Keys (../data-format/message-header.md#encrypted-
#    data-key-entries): MUST be the serialization of the encrypted data
#    keys (../framework/structures.md#encrypted-data-keys) in the
#    encryption materials (../framework/structures.md#encryption-
#    materials)
# 
# *  Content Type (../data-format/message-header.md#content-type): MUST
#    be 02 (../data-format/message-header.md#supported-content-types)
# 
# *  Frame Length (../data-format/message-header.md#frame-length): MUST
#    be the value of the frame size determined above.
# 
# *  Algorithm Suite Data (../data-format/message-header.md#algorithm-
#    suite-data): MUST be the value of the commit key (../framework/
#    algorithm-suites.md#commit-key) derived according to the algorithm
#    suites commit key derivation settings (../framework/algorithm-
#    suites.md#algorithm-suites-commit-key-derivation-settings).
# 
# If the message format version associated with the algorithm suite
# (../framework/algorithm-suites.md#supported-algorithm-suites) is 1.0
# then the message header body (../data-format/message-
# header.md#header-body-version-1-0) MUST be serialized with the
# following specifics:
# 
# *  Version (../data-format/message-header.md#version-1): MUST have a
#    value corresponding to 1.0 (../data-format/message-
#    header.md#supported-versions)
# 
# *  Type (../data-format/message-header.md#type): MUST have a value
#    corresponding to Customer Authenticated Encrypted Data (../data-
#    format/message-header.md#supported-types)
# 
# *  Algorithm Suite ID (../data-format/message-header.md#algorithm-
#    suite-id): MUST correspond to the algorithm suite (../framework/
#    algorithm-suites.md) used in this behavior
# 
# *  Message ID (../data-format/message-header.md#message-id): The
#    process used to generate this identifier MUST use a good source of
#    randomness to make the chance of duplicate identifiers negligible.
# 
# *  AAD (../data-format/message-header.md#aad): MUST be the
#    serialization of the encryption context (../framework/
#    structures.md#encryption-context) in the encryption materials
#    (../framework/structures.md#encryption-materials)
# 
# *  Encrypted Data Keys (../data-format/message-header.md#encrypted-
#    data-key-entries): MUST be the serialization of the encrypted data
#    keys (../framework/structures.md#encrypted-data-keys) in the
#    encryption materials (../framework/structures.md#encryption-
#    materials)
# 
# *  Content Type (../data-format/message-header.md#content-type): MUST
#    be 02 (../data-format/message-header.md#supported-content-types)
# 
# *  IV Length (../data-format/message-header.md#iv-length): MUST match
#    the IV length (../framework/algorithm-suites.md#iv-length)
#    specified by the algorithm suite (../framework/algorithm-
#    suites.md)
# 
# *  Frame Length (../data-format/message-header.md#frame-length): MUST
#    be the value of the frame size determined above.
# 
# After serializing the message header body, this operation MUST
# calculate an authentication tag (../data-format/message-
# header.md#authentication-tag) over the message header body.  The
# value of this MUST be the output of the authenticated encryption
# algorithm (../framework/algorithm-suites.md#encryption-algorithm)
# specified by the algorithm suite (../framework/algorithm-suites.md),
# with the following inputs:
# 
# *  The AAD is the serialized message header body (../data-format/
#    message-header.md#header-body).
# 
# *  The IV has a value of 0.
# 
# *  The cipherkey is the derived data key
# 
# *  The plaintext is an empty byte array
# 
# With the authentication tag calculated, if the message format version
# associated with the algorithm suite (../framework/algorithm-
# suites.md#supported-algorithm-suites) is 2.0, this operation MUST
# serialize the message header authentication (../data-format/message-
# header.md#header-authentication-version-2-0) with the following
# specifics:
# 
# *  Authentication Tag (../data-format/message-
#    header.md#authentication-tag): MUST have the value of the
#    authentication tag calculated above.
# 
# If the message format version associated with the algorithm suite
# (../framework/algorithm-suites.md#supported-algorithm-suites) is 1.0
# this operation MUST serialize the message header authentication
# (../data-format/message-header.md#header-authentication-version-1-0)
# with the following specifics:
# 
# *  IV (../data-format/message-header.md#iv): MUST have the value of
#    the IV used in the calculation above, padded to the IV length
#    (../data-format/message-header.md#iv-length) with 0.
# 
# *  Authentication Tag (../data-format/message-
#    header.md#authentication-tag): MUST have the value of the
#    authentication tag calculated above.
# 
# The serialized bytes MUST NOT be released until the entire message
# header has been serialized If this operation is streaming the
# encrypted message and the entire message header has been serialized,
# the serialized message header SHOULD be released.
# 
# The encrypted message output by this operation MUST have a message
# header equal to the message header calculated in this step.
# 
# If the algorithm suite contains a signature algorithm and this
# operation is streaming (streaming.md) the encrypted message output to
# the caller, this operation MUST input the serialized header to the
# signature algorithm as soon as it is serialized, such that the
# serialized header isn't required to remain in memory to construct the
# signature (Section 2.7.2).

[[spec]]
level = "MUST"
quote = '''
Before encrypting input plaintext, this operation MUST serialize the
message header body (../data-format/message-header.md).
'''

[[spec]]
level = "MUST"
quote = '''
The message
format version (../data-format/message-header.md#supported-versions)
MUST be associated with the algorithm suite (../framework/algorithm-
suites.md#supported-algorithm-suites).
'''

[[spec]]
level = "MUST"
quote = '''
./data-format/message-
header.md#header-body-version-1-0) MUST be serialized with the
following specifics:
'''

[[spec]]
level = "MUST"
quote = '''
*  Version (../data-format/message-header.md#version-1): MUST have a
value corresponding to 2.0 (../data-format/message-
header.md#supported-versions)
'''

[[spec]]
level = "MUST"
quote = '''
*  Algorithm Suite ID (../data-format/message-header.md#algorithm-
suite-id): MUST correspond to the algorithm suite (../framework/
algorithm-suites.md) used in this behavior
'''

[[spec]]
level = "MUST"
quote = '''
*  Message ID (../data-format/message-header.md#message-id): The
process used to generate this identifier MUST use a good source of
randomness to make the chance of duplicate identifiers negligible.
'''

[[spec]]
level = "MUST"
quote = '''
*  AAD (../data-format/message-header.md#aad): MUST be the
serialization of the encryption context (../framework/
structures.md#encryption-context) in the encryption materials
(../framework/structures.md#encryption-materials)
'''

[[spec]]
level = "MUST"
quote = '''
*  Encrypted Data Keys (../data-format/message-header.md#encrypted-
data-key-entries): MUST be the serialization of the encrypted data
keys (../framework/structures.md#encrypted-data-keys) in the
encryption materials (../framework/structures.md#encryption-
materials)
'''

[[spec]]
level = "MUST"
quote = '''
*  Content Type (../data-format/message-header.md#content-type): MUST
be 02 (../data-format/message-header.md#supported-content-types)
'''

[[spec]]
level = "MUST"
quote = '''
*  Frame Length (../data-format/message-header.md#frame-length): MUST
be the value of the frame size determined above.
'''

[[spec]]
level = "MUST"
quote = '''
*  Algorithm Suite Data (../data-format/message-header.md#algorithm-
suite-data): MUST be the value of the commit key (../framework/
algorithm-suites.md#commit-key) derived according to the algorithm
suites commit key derivation settings (../framework/algorithm-
suites.md#algorithm-suites-commit-key-derivation-settings).
'''

[[spec]]
level = "MUST"
quote = '''
./data-format/message-
header.md#header-body-version-1-0) MUST be serialized with the
following specifics:
'''

[[spec]]
level = "MUST"
quote = '''
*  Version (../data-format/message-header.md#version-1): MUST have a
value corresponding to 1.0 (../data-format/message-
header.md#supported-versions)
'''

[[spec]]
level = "MUST"
quote = '''
*  Type (../data-format/message-header.md#type): MUST have a value
corresponding to Customer Authenticated Encrypted Data (../data-
format/message-header.md#supported-types)
'''

[[spec]]
level = "MUST"
quote = '''
*  Algorithm Suite ID (../data-format/message-header.md#algorithm-
suite-id): MUST correspond to the algorithm suite (../framework/
algorithm-suites.md) used in this behavior
'''

[[spec]]
level = "MUST"
quote = '''
*  Message ID (../data-format/message-header.md#message-id): The
process used to generate this identifier MUST use a good source of
randomness to make the chance of duplicate identifiers negligible.
'''

[[spec]]
level = "MUST"
quote = '''
*  AAD (../data-format/message-header.md#aad): MUST be the
serialization of the encryption context (../framework/
structures.md#encryption-context) in the encryption materials
(../framework/structures.md#encryption-materials)
'''

[[spec]]
level = "MUST"
quote = '''
*  Encrypted Data Keys (../data-format/message-header.md#encrypted-
data-key-entries): MUST be the serialization of the encrypted data
keys (../framework/structures.md#encrypted-data-keys) in the
encryption materials (../framework/structures.md#encryption-
materials)
'''

[[spec]]
level = "MUST"
quote = '''
*  Content Type (../data-format/message-header.md#content-type): MUST
be 02 (../data-format/message-header.md#supported-content-types)
'''

[[spec]]
level = "MUST"
quote = '''
*  IV Length (../data-format/message-header.md#iv-length): MUST match
the IV length (../framework/algorithm-suites.md#iv-length)
specified by the algorithm suite (../framework/algorithm-
suites.md)
'''

[[spec]]
level = "MUST"
quote = '''
*  Frame Length (../data-format/message-header.md#frame-length): MUST
be the value of the frame size determined above.
'''

[[spec]]
level = "MUST"
quote = '''
After serializing the message header body, this operation MUST
calculate an authentication tag (../data-format/message-
header.md#authentication-tag) over the message header body.
'''

[[spec]]
level = "MUST"
quote = '''
The
value of this MUST be the output of the authenticated encryption
algorithm (../framework/algorithm-suites.md#encryption-algorithm)
specified by the algorithm suite (../framework/algorithm-suites.md),
with the following inputs:
'''

[[spec]]
level = "MUST"
quote = '''
./framework/algorithm-
suites.md#supported-algorithm-suites) is 2.0, this operation MUST
serialize the message header authentication (../data-format/message-
header.md#header-authentication-version-2-0) with the following
specifics:
'''

[[spec]]
level = "MUST"
quote = '''
./data-format/message-
header.md#authentication-tag): MUST have the value of the
authentication tag calculated above.
'''

[[spec]]
level = "MUST"
quote = '''
If the message format version associated with the algorithm suite
(../framework/algorithm-suites.md#supported-algorithm-suites) is 1.0
this operation MUST serialize the message header authentication
(../data-format/message-header.md#header-authentication-version-1-0)
with the following specifics:
'''

[[spec]]
level = "MUST"
quote = '''
*  IV (../data-format/message-header.md#iv): MUST have the value of
the IV used in the calculation above, padded to the IV length
(../data-format/message-header.md#iv-length) with 0.
'''

[[spec]]
level = "MUST"
quote = '''
./data-format/message-
header.md#authentication-tag): MUST have the value of the
authentication tag calculated above.
'''

[[spec]]
level = "MUST"
quote = '''
The serialized bytes MUST NOT be released until the entire message
header has been serialized If this operation is streaming the
encrypted message and the entire message header has been serialized,
the serialized message header SHOULD be released.
'''

[[spec]]
level = "MUST"
quote = '''
The encrypted message output by this operation MUST have a message
header equal to the message header calculated in this step.
'''

[[spec]]
level = "MUST"
quote = '''
If the algorithm suite contains a signature algorithm and this
operation is streaming (streaming.md) the encrypted message output to
the caller, this operation MUST input the serialized header to the
signature algorithm as soon as it is serialized, such that the
serialized header isn't required to remain in memory to construct the
signature (Section 2.7.2).
'''

