target = "compliance/client-apis/encrypt.txt#2.6"

# 2.6.  Behavior
#
# The Encrypt operation is divided into several distinct steps:
# 
# *  Get the encryption materials (Section 2.6.1)
# 
# *  Construct the header (Section 2.6.2)
# 
# *  Construct the body (Section 2.7)
# 
# *  Construct the signature (Section 2.7.2)
# 
#    -  If the encryption materials gathered (Section 2.6.1) has a
#       algorithm suite including a signature algorithm (../framework/
#       algorithm-suites.md#signature-algorithm), the encrypt operation
#       MUST perform this step.  Otherwise the encrypt operation MUST
#       NOT perform this step.
# 
# This operation MUST perform all the above steps unless otherwise
# specified, and it MUST perform them in the above order.
# 
# These steps calculate and serialize the components of the output
# encrypted message (Section 2.5.1).  Any data that is not specified
# within the message format (../data-format/message.md) MUST NOT be
# added to the output message.
# 
# If any of these steps fails, this operation MUST halt and indicate a
# failure to the caller.

[[spec]]
level = "MUST"
quote = '''
./framework/
algorithm-suites.md#signature-algorithm), the encrypt operation
MUST perform this step.
'''

[[spec]]
level = "MUST"
quote = '''
Otherwise the encrypt operation MUST
NOT perform this step.
'''

[[spec]]
level = "MUST"
quote = '''
This operation MUST perform all the above steps unless otherwise
specified, and it MUST perform them in the above order.
'''

[[spec]]
level = "MUST"
quote = '''
This operation MUST perform all the above steps unless otherwise
specified, and it MUST perform them in the above order.
'''

[[spec]]
level = "MUST"
quote = '''
Any data that is not specified
within the message format (../data-format/message.md) MUST NOT be
added to the output message.
'''

[[spec]]
level = "MUST"
quote = '''
If any of these steps fails, this operation MUST halt and indicate a
failure to the caller.
'''

