target = "compliance/client-apis/encrypt.txt#2.7.1"

# 2.7.1.  Construct a frame
#
# To construct a regular or final frame that represents the next frame
# in the encrypted message's body, this operation MUST calculate the
# encrypted content and an authentication tag using the authenticated
# encryption algorithm (../framework/algorithm-suites.md#encryption-
# algorithm) specified by the algorithm suite (../framework/algorithm-
# suites.md), with the following inputs:
# 
# *  The AAD is the serialized message body AAD (../data-format/
#    message-body-aad.md), constructed as follows:
# 
#    -  The message ID (../data-format/message-body-aad.md#message-id)
#       is the same as the message ID (../data-frame/message-
#       header.md#message-id) serialized in the header of this message.
# 
#    -  The Body AAD Content (../data-format/message-body-aad.md#body-
#       aad-content) depends on whether the thing being encrypted is a
#       regular frame or final frame.  Refer to Message Body AAD
#       (../data-format/message-body-aad.md) specification for more
#       information.
# 
#    -  The sequence number (../data-format/message-body-
#       aad.md#sequence-number) is the sequence number of the frame
#       being encrypted.  If this is the first frame sequentially, this
#       value MUST be 1.  Otherwise, this value MUST be 1 greater than
#       the value of the sequence number of the previous frame.
# 
#    -  The content length (../data-format/message-body-aad.md#content-
#       length) MUST have a value equal to the length of the plaintext
#       being encrypted.
# 
#       o  For a regular frame the length of this plaintext MUST equal
#          the frame length.
# 
#       o  For a final frame this MUST be the length of the remaining
#          plaintext bytes which have not yet been encrypted, whose
#          length MUST be equal to or less than the frame length.
# 
# *  The IV is the sequence number (../data-format/message-body-
#    aad.md#sequence-number) used in the message body AAD above, padded
#    to the IV length (../data-format/message-header.md#iv-length).
# 
# *  The cipherkey is the derived data key
# 
# *  The plaintext is the next subsequence of consumable plaintext
#    bytes that have not yet been encrypted.
# 
#    -  For a regular frame the length of this plaintext subsequence
#       MUST equal the frame length.
# 
#    -  For a final frame this MUST be the remaining plaintext bytes
#       which have not yet been encrypted, whose length MUST be equal
#       to or less than the frame length.
# 
# This operation MUST serialize a regular frame or final frame with the
# following specifics:
# 
# *  Sequence Number (../data-format/message-body.md#sequence-number):
#    MUST be the sequence number of this frame, as determined above.
# 
# *  IV (../data-format/message-body.md#iv): MUST be the IV used when
#    calculating the encrypted content above
# 
# *  Encrypted Content (../data-format/message-body.md#encrypted-
#    content): MUST be the encrypted content calculated above.
# 
# *  Authentication Tag (../data-format/message-body.md#authentication-
#    tag): MUST be the authentication tag output when calculating the
#    encrypted content above.
# 
# The above serialized bytes MUST NOT be released until the entire
# frame has been serialized.  If this operation is streaming the
# encrypted message and the entire frame has been serialized, the
# serialized frame SHOULD be released.
# 
# If the algorithm suite contains a signature algorithm and this
# operation is streaming (streaming.md) the encrypted message output to
# the caller, this operation MUST input the serialized frame to the
# signature algorithm as soon as it is serialized, such that the
# serialized frame isn't required to remain in memory to construct the
# signature (Section 2.7.2).

[[spec]]
level = "MUST"
quote = '''
To construct a regular or final frame that represents the next frame
in the encrypted message's body, this operation MUST calculate the
encrypted content and an authentication tag using the authenticated
encryption algorithm (../framework/algorithm-suites.md#encryption-
algorithm) specified by the algorithm suite (../framework/algorithm-
suites.md), with the following inputs:
'''

[[spec]]
level = "MUST"
quote = '''
If this is the first frame sequentially, this
value MUST be 1.
'''

[[spec]]
level = "MUST"
quote = '''
Otherwise, this value MUST be 1 greater than
the value of the sequence number of the previous frame.
'''

[[spec]]
level = "MUST"
quote = '''
-  The content length (../data-format/message-body-aad.md#content-
length) MUST have a value equal to the length of the plaintext
being encrypted.
'''

[[spec]]
level = "MUST"
quote = '''
o  For a regular frame the length of this plaintext MUST equal
the frame length.
'''

[[spec]]
level = "MUST"
quote = '''
o  For a final frame this MUST be the length of the remaining
plaintext bytes which have not yet been encrypted, whose
length MUST be equal to or less than the frame length.
'''

[[spec]]
level = "MUST"
quote = '''
o  For a final frame this MUST be the length of the remaining
plaintext bytes which have not yet been encrypted, whose
length MUST be equal to or less than the frame length.
'''

[[spec]]
level = "MUST"
quote = '''
-  For a regular frame the length of this plaintext subsequence
MUST equal the frame length.
'''

[[spec]]
level = "MUST"
quote = '''
-  For a final frame this MUST be the remaining plaintext bytes
which have not yet been encrypted, whose length MUST be equal
to or less than the frame length.
'''

[[spec]]
level = "MUST"
quote = '''
-  For a final frame this MUST be the remaining plaintext bytes
which have not yet been encrypted, whose length MUST be equal
to or less than the frame length.
'''

[[spec]]
level = "MUST"
quote = '''
This operation MUST serialize a regular frame or final frame with the
following specifics:
'''

[[spec]]
level = "MUST"
quote = '''
*  Sequence Number (../data-format/message-body.md#sequence-number):
MUST be the sequence number of this frame, as determined above.
'''

[[spec]]
level = "MUST"
quote = '''
*  IV (../data-format/message-body.md#iv): MUST be the IV used when
calculating the encrypted content above
'''

[[spec]]
level = "MUST"
quote = '''
*  Encrypted Content (../data-format/message-body.md#encrypted-
content): MUST be the encrypted content calculated above.
'''

[[spec]]
level = "MUST"
quote = '''
*  Authentication Tag (../data-format/message-body.md#authentication-
tag): MUST be the authentication tag output when calculating the
encrypted content above.
'''

[[spec]]
level = "MUST"
quote = '''
The above serialized bytes MUST NOT be released until the entire
frame has been serialized.
'''

[[spec]]
level = "SHOULD"
quote = '''
If this operation is streaming the
encrypted message and the entire frame has been serialized, the
serialized frame SHOULD be released.
'''

[[spec]]
level = "MUST"
quote = '''
If the algorithm suite contains a signature algorithm and this
operation is streaming (streaming.md) the encrypted message output to
the caller, this operation MUST input the serialized frame to the
signature algorithm as soon as it is serialized, such that the
serialized frame isn't required to remain in memory to construct the
signature (Section 2.7.2).
'''

