target = "compliance/framework/master-key-provider-interface.txt#2.3.2"

# 2.3.2.  Consistency
#
# This specification defines the common behavior between the two
# implementations that determine the REQUIRED functionality.
# 
# Other specifics of behavior and API vary between the two
# implementations.

[[spec]]
level = "MUST"
quote = '''
This specification defines the common behavior between the two
implementations that determine the REQUIRED functionality.
'''

