target = "compliance/framework/master-key-provider-interface.txt#2.5.3"

# 2.5.3.  Decrypt Data Key
#
# This interface is used to decrypt a data key.
# 
# The master key provider SHOULD attempt to decrypt the data key by
# passing the request to any master keys that it has access to until it
# has either exhausted available master keys or obtained a plaintext
# data key.
# 
# Inputs to this interface MUST include the algorithm suite, the
# encryption context, and a list of encrypted data keys.
# 
# The output of this interface MUST include the decrypted data key and
# information that can identify which master key decrypted the data
# key.
# 
# If the master key provider cannot decrypt the data key, the call MUST
# result in an error.

[[spec]]
level = "SHOULD"
quote = '''
The master key provider SHOULD attempt to decrypt the data key by
passing the request to any master keys that it has access to until it
has either exhausted available master keys or obtained a plaintext
data key.
'''

[[spec]]
level = "MUST"
quote = '''
Inputs to this interface MUST include the algorithm suite, the
encryption context, and a list of encrypted data keys.
'''

[[spec]]
level = "MUST"
quote = '''
The output of this interface MUST include the decrypted data key and
information that can identify which master key decrypted the data
key.
'''

[[spec]]
level = "MUST"
quote = '''
If the master key provider cannot decrypt the data key, the call MUST
result in an error.
'''

