target = "compliance/framework/master-key-provider-interface.txt#2.5.1"

# 2.5.1.  Get Master Key
#
# This interface provides a way for a master key provider to return
# master keys.
# 
# An implementation MUST support master key selection by key ID.
# 
# An implementation MAY support master key selection by provider info
# or provider ID.
# 
# The output of this interface MUST be a master key.
# 
# If the master key provider cannot locate an appropriate master key,
# the call MUST result in an error.

[[spec]]
level = "MUST"
quote = '''
An implementation MUST support master key selection by key ID.
'''

[[spec]]
level = "MAY"
quote = '''
An implementation MAY support master key selection by provider info
or provider ID.
'''

[[spec]]
level = "MUST"
quote = '''
The output of this interface MUST be a master key.
'''

[[spec]]
level = "MUST"
quote = '''
If the master key provider cannot locate an appropriate master key,
the call MUST result in an error.
'''

