target = "compliance/framework/cryptographic-materials-cache.txt#2.3"

# 2.3.  Overview
#
# Cryptographic materials cache (CMC) is used by the caching
# cryptographic materials manager (CMM) (caching-cmm.md) to store
# cryptographic materials for reuse.  This document describes the
# interface that all CMCs MUST implement.

[[spec]]
level = "MUST"
quote = '''
This document describes the
interface that all CMCs MUST implement.
'''

