target = "compliance/client-apis/decrypt.txt#2.3"

# 2.3.  Overview
#
# This document describes the AWS Encryption SDK's (ESDK's) decrypt
# operation, used for decrypting a message that was previously
# encrypted by the ESDK.
# 
# Any client provided by the AWS Encryption SDK that performs
# decryption of encrypted messages MUST follow this specification for
# decryption.

[[spec]]
level = "MUST"
quote = '''
Any client provided by the AWS Encryption SDK that performs
decryption of encrypted messages MUST follow this specification for
decryption.
'''

