target = "compliance/client-apis/decrypt.txt#2.4.2"

# 2.4.2.  Authenticated Data
#
# Plaintext or associated data is considered authenticated if the
# associated authentication tag (../data-format/message-
# body.md#authentication-tag) is successfully checked as defined by the
# algorithm suite indicated in the message header.
# 
# This operation MUST NOT release any unauthenticated plaintext or
# unauthenticated associated data.

[[spec]]
level = "MUST"
quote = '''
This operation MUST NOT release any unauthenticated plaintext or
unauthenticated associated data.
'''

