target = "compliance/client-apis/decrypt.txt#2.5.2"

# 2.5.2.  Cryptographic Materials Manager
#
# A CMM that implements the CMM interface (../framework/cmm-
# interface.md).
# 
# This CMM MUST obtain the decryption materials (../framework/
# structures.md#decryption-materials) required for decryption.

[[spec]]
level = "MUST"
quote = '''
This CMM MUST obtain the decryption materials (../framework/
structures.md#decryption-materials) required for decryption.
'''

