target = "compliance/client-apis/decrypt.txt#2.5.1.1"

# 2.5.1.1.  Encrypted Message Format
#
# The message format is a binary format, but it is a common mistake for
# users to attempt decryption on the Base64 encoding of this data
# instead.  Because the first two bytes of the message format have a
# very limited set of possible values (currently they are in fact
# fixed), the first two bytes of the Base64 encoding of a valid message
# are also simple to recognize.
# 
# To make diagnosing this mistake easier, implementations SHOULD detect
# the first two bytes of the Base64 encoding of any supported message
# versions (../data-format/message-header.md#version-1) and types
# (../data-format/message-header.md#type) and fail with a more specific
# error message.  In particular, the hex values to detect for the
# current set of versions and types are:
# 
# +========================+=========================+================+
# | Version and type (hex) | Base64 encoding         | Base64         |
# |                        | (ascii)                 | encoding (hex) |
# +========================+=========================+================+
# | 01 80                  | A Y ...                 | 41 59 ...      |
# +------------------------+-------------------------+----------------+
# 
#                                Table 2
# 
# Note that the bytes that follow the initial two in the Base64
# encoding partially depend on subsequent bytes in the binary message
# format and hence are not as predictable.

[[spec]]
level = "SHOULD"
quote = '''
To make diagnosing this mistake easier, implementations SHOULD detect
the first two bytes of the Base64 encoding of any supported message
versions (../data-format/message-header.md#version-1) and types
(../data-format/message-header.md#type) and fail with a more specific
error message.
'''

