target = "compliance/client-apis/decrypt.txt#2.6.2"

# 2.6.2.  Encryption Context
#
# The encryption context (../framework/structures.md#encryption-
# context) that is used as additional authenticated data during the
# decryption of the input encrypted message (Section 2.5.1).
# 
# This output MAY be satisfied by outputting a parsed header
# (Section 2.6.4) containing this value.

[[spec]]
level = "MAY"
quote = '''
This output MAY be satisfied by outputting a parsed header
(Section 2.6.4) containing this value.
'''

