target = "compliance/client-apis/decrypt.txt#2.6.3"

# 2.6.3.  Algorithm Suite
#
# The algorithm suite (../framework/algorithm-suites.md) that is used
# to decrypt the input encrypted message (Section 2.5.1).
# 
# This output MAY be satisfied by outputting a parsed header
# (Section 2.6.4) containing this value.

[[spec]]
level = "MAY"
quote = '''
This output MAY be satisfied by outputting a parsed header
(Section 2.6.4) containing this value.
'''

