target = "compliance/client-apis/decrypt.txt#2.6.1"

# 2.6.1.  Plaintext
#
# The decrypted data.
# 
# This operation MAY stream (streaming.md) the plaintext as output.
# 
# If an implementation requires holding the entire encrypted message in
# memory in order to perform this operation, that implementation SHOULD
# NOT provide an API that allows the caller to stream the encrypted
# message.

[[spec]]
level = "MAY"
quote = '''
This operation MAY stream (streaming.md) the plaintext as output.
'''

[[spec]]
level = "SHOULD"
quote = '''
If an implementation requires holding the entire encrypted message in
memory in order to perform this operation, that implementation SHOULD
NOT provide an API that allows the caller to stream the encrypted
message.
'''

