target = "compliance/client-apis/decrypt.txt#2.7.3"

# 2.7.3.  Verify the header
#
# Once a valid message header is deserialized and decryption materials
# are available, this operation MUST validate the message header body
# (../data-format/message-header.md#header-body) by using the
# authenticated encryption algorithm (../framework/algorithm-
# suites.md#encryption-algorithm) to decrypt with the following inputs:
# 
# *  the AAD is the serialized message header body (../data-format/
#    message-header.md#header-body).
# 
# *  the IV is the value serialized in the message header's IV field
#    (../data-format/message-header#iv).
# 
# *  the cipherkey is the derived data key
# 
# *  the ciphertext is an empty byte array
# 
# *  the tag is the value serialized in the message header's
#    authentication tag field (../data-format/message-
#    header.md#authentication-tag)
# 
# If this tag verification fails, this operation MUST immediately halt
# and fail.
# 
# If the input encrypted message is being streamed (streaming.md) to
# this operation:
# 
# *  This operation SHOULD release the parsed encryption context
#    (Section 2.6.2), algorithm suite ID (../data-format/message-
#    header.md#algorithm-suite-id), and other header information
#    (Section 2.6.4) as soon as tag verification succeeds.  However, if
#    this operation is using an algorithm suite with a signature
#    algorithm all released output MUST NOT be considered signed data
#    until this operation successfully completes.  See security
#    considerations (Section 2.8) below.
# 
# *  This operation SHOULD input the serialized header to the signature
#    algorithm as soon as it is deserialized, such that the serialized
#    frame isn't required to remain in memory to verify the signature
#    (Section 2.7.5).

[[spec]]
level = "MUST"
quote = '''
Once a valid message header is deserialized and decryption materials
are available, this operation MUST validate the message header body
(../data-format/message-header.md#header-body) by using the
authenticated encryption algorithm (../framework/algorithm-
suites.md#encryption-algorithm) to decrypt with the following inputs:
'''

[[spec]]
level = "MUST"
quote = '''
If this tag verification fails, this operation MUST immediately halt
and fail.
'''

[[spec]]
level = "SHOULD"
quote = '''
*  This operation SHOULD release the parsed encryption context
(Section 2.6.2), algorithm suite ID (../data-format/message-
header.md#algorithm-suite-id), and other header information
(Section 2.6.4) as soon as tag verification succeeds.
'''

[[spec]]
level = "MUST"
quote = '''
However, if
this operation is using an algorithm suite with a signature
algorithm all released output MUST NOT be considered signed data
until this operation successfully completes.
'''

[[spec]]
level = "SHOULD"
quote = '''
*  This operation SHOULD input the serialized header to the signature
algorithm as soon as it is deserialized, such that the serialized
frame isn't required to remain in memory to verify the signature
(Section 2.7.5).
'''

