target = "compliance/client-apis/decrypt.txt#2.7.2"

# 2.7.2.  Get the decryption materials
#
# If the parsed algorithm suite ID (../data-format/message-
# header.md#algorithm-suite-id) is not supported by the commitment
# policy (client.md#commitment-policy) configured in the client
# (client.md) decrypt MUST yield an error.
# 
# To verify the message header and decrypt the message body, a set of
# valid decryption materials is required.
# 
# This operation MUST obtain this set of decryption materials
# (../framework/structures.md#decryption-materials), by calling Decrypt
# Materials (../framework/cmm-interface.md#decrypt-materials) on a CMM
# (../framework/cmm-interface.md).
# 
# The CMM used MUST be the input CMM, if supplied.  If a CMM is not
# supplied as the input, the decrypt operation MUST construct a default
# CMM (../framework/default-cmm.md) from the input keyring
# (../framework/keyring-interface.md).
# 
# The call to the CMM's Decrypt Materials (../framework/cmm-
# interface.md#decrypt-materials) operation MUST be constructed as
# follows:
# 
# *  Encryption Context: This is the parsed encryption context
#    (../data-format/message-header.md#aad) from the message header.
# 
# *  Algorithm Suite ID: This is the parsed algorithm suite ID
#    (../data-format/message-header.md#algorithm-suite-id) from the
#    message header.
# 
# *  Encrypted Data Keys: This is the parsed encrypted data keys
#    (../data-format/message-header#encrypted-data-keys) from the
#    message header.
# 
# The data key used as input for all decryption described below is a
# data key derived from the plaintext data key included in the
# decryption materials (../framework/structures.md#decryption-
# materials).  The algorithm suite used as input for all decryption
# described below is a algorithm suite included in the decryption
# materials (../framework/structures.md#decryption-materials).  If the
# algorithm suite is not supported by the commitment policy
# (client.md#commitment-policy) configured in the client (client.md)
# decrypt MUST yield an error.  If the algorithm suite (../framework/
# algorithm-suites.md#algorithm-suites-encryption-key-derivation-
# settings) supports key commitment (../framework/algorithm-
# suites.md#key-commitment) then the commit key (../framework/
# algorithm-suites.md#commit-key) MUST be derived from the plaintext
# data key using the commit key derivation (../framework/algorithm-
# suites.md#algorithm-suites-commit-key-derivation-settings).  The
# derived commit key MUST equal the commit key stored in the message
# header.  The algorithm suite used to derive a data key from the
# plaintext data key MUST be the key derivation algorithm
# (../framework/algorithm-suites.md#key-derivation-algorithm) included
# in the algorithm suite (../framework/algorithm-suites.md) associated
# with the returned decryption materials.  This document refers to the
# output of the key derivation algorithm as the derived data key.  Note
# that if the key derivation algorithm is the identity KDF
# (../framework/algorithm-suites.md#identity-kdf), then the derived
# data key is the same as the plaintext data key.

[[spec]]
level = "MUST"
quote = '''
./data-format/message-
header.md#algorithm-suite-id) is not supported by the commitment
policy (client.md#commitment-policy) configured in the client
(client.md) decrypt MUST yield an error.
'''

[[spec]]
level = "MUST"
quote = '''
This operation MUST obtain this set of decryption materials
(../framework/structures.md#decryption-materials), by calling Decrypt
Materials (../framework/cmm-interface.md#decrypt-materials) on a CMM
(../framework/cmm-interface.md).
'''

[[spec]]
level = "MUST"
quote = '''
The CMM used MUST be the input CMM, if supplied.
'''

[[spec]]
level = "MUST"
quote = '''
If a CMM is not
supplied as the input, the decrypt operation MUST construct a default
CMM (../framework/default-cmm.md) from the input keyring
(../framework/keyring-interface.md).
'''

[[spec]]
level = "MUST"
quote = '''
./framework/cmm-
interface.md#decrypt-materials) operation MUST be constructed as
follows:
'''

[[spec]]
level = "MUST"
quote = '''
If the
algorithm suite is not supported by the commitment policy
(client.md#commitment-policy) configured in the client (client.md)
decrypt MUST yield an error.
'''

[[spec]]
level = "MUST"
quote = '''
./framework/
algorithm-suites.md#commit-key) MUST be derived from the plaintext
data key using the commit key derivation (../framework/algorithm-
suites.md#algorithm-suites-commit-key-derivation-settings).
'''

[[spec]]
level = "MUST"
quote = '''
The
derived commit key MUST equal the commit key stored in the message
header.
'''

[[spec]]
level = "MUST"
quote = '''
The algorithm suite used to derive a data key from the
plaintext data key MUST be the key derivation algorithm
(../framework/algorithm-suites.md#key-derivation-algorithm) included
in the algorithm suite (../framework/algorithm-suites.md) associated
with the returned decryption materials.
'''

