target = "compliance/client-apis/decrypt.txt#2.8"

# 2.8.  Security Considerations
#
# If this operation is streaming (streaming.md) output to the caller
# and is decrypting messages created with an algorithm suite including
# a signature algorithm, any released plaintext MUST NOT be considered
# signed data until this operation finishes successfully.
# 
# This means that callers that process such released plaintext MUST NOT
# consider any processing successful until this operation completes
# successfully.  Additionally, if this operation fails, callers MUST
# discard the released plaintext and encryption context and MUST
# rollback any processing done due to the released plaintext or
# encryption context.

[[spec]]
level = "MUST"
quote = '''
If this operation is streaming (streaming.md) output to the caller
and is decrypting messages created with an algorithm suite including
a signature algorithm, any released plaintext MUST NOT be considered
signed data until this operation finishes successfully.
'''

[[spec]]
level = "MUST"
quote = '''
This means that callers that process such released plaintext MUST NOT
consider any processing successful until this operation completes
successfully.
'''

[[spec]]
level = "MUST"
quote = '''
Additionally, if this operation fails, callers MUST
discard the released plaintext and encryption context and MUST
rollback any processing done due to the released plaintext or
encryption context.
'''

[[spec]]
level = "MUST"
quote = '''
Additionally, if this operation fails, callers MUST
discard the released plaintext and encryption context and MUST
rollback any processing done due to the released plaintext or
encryption context.
'''

