target = "compliance/framework/caching-cmm.txt#2.5.5"

# 2.5.5.  Limit Bytes
#
# The maximum number of bytes that MAY be encrypted by a single data
# key.  It is interpreted as UInt64.  If this parameter is not set, the
# caching CMM MUST set it to a value no more than 2^63-1.  This
# parameter is set as an additional security thresholds to ensure that
# the data keys expire and are refreshed periodically.

[[spec]]
level = "MAY"
quote = '''
The maximum number of bytes that MAY be encrypted by a single data
key.
'''

[[spec]]
level = "MUST"
quote = '''
If this parameter is not set, the
caching CMM MUST set it to a value no more than 2^63-1.
'''

