target = "compliance/framework/caching-cmm.txt#2.5"

# 2.5.  Initialization
#
# On caching CMM initialization, the caller MUST provide the following
# values:
# 
# *  Underlying Cryptographic Materials Cache (CMC) (Section 2.5.1)
# 
# *  Cache Limit TTL (Section 2.5.3)
# 
# Additionally, the caller MUST provide one of the following values:
# 
# *  Underlying Cryptographic Materials Manager (CMM) (Section 2.5.2)
# 
# *  Keyring (keyring-interface.md)
# 
# If the caller provides a keyring, then the caching CMM MUST set its
# underlying CMM to a default CMM (default-cmm.md) initialized with the
# keyring.
# 
# Finally, the caching CMM MUST optionally accept the following values:
# 
# *  Partition ID (Section 2.5.4)
# 
# *  Limit Bytes (Section 2.5.5)
# 
# *  Limit Messages (Section 2.5.6)

[[spec]]
level = "MUST"
quote = '''
On caching CMM initialization, the caller MUST provide the following
values:
'''

[[spec]]
level = "MUST"
quote = '''
Additionally, the caller MUST provide one of the following values:
'''

[[spec]]
level = "MUST"
quote = '''
If the caller provides a keyring, then the caching CMM MUST set its
underlying CMM to a default CMM (default-cmm.md) initialized with the
keyring.
'''

[[spec]]
level = "MUST"
quote = '''
Finally, the caching CMM MUST optionally accept the following values:
'''

