target = "compliance/framework/caching-cmm.txt#2.5.6"

# 2.5.6.  Limit Messages
#
# The maximum number of messages that MAY be encrypted by a single data
# key.  It is interpreted as Uint64.  If this parameter is not set, the
# caching CMM MUST set it to 2^32.  This parameter is set as an
# additional security thresholds to ensure that the data keys expire
# and are refreshed periodically.
# 
# The caching CMM MUST provide a structure as defined below, to track
# usage statistics.

[[spec]]
level = "MAY"
quote = '''
The maximum number of messages that MAY be encrypted by a single data
key.
'''

[[spec]]
level = "MUST"
quote = '''
If this parameter is not set, the
caching CMM MUST set it to 2^32.
'''

[[spec]]
level = "MUST"
quote = '''
The caching CMM MUST provide a structure as defined below, to track
usage statistics.
'''

