target = "compliance/framework/caching-cmm.txt#2.5.3"

# 2.5.3.  Cache Limit TTL
#
# The maximum amount of time in seconds that a data key can be used.
# The Caching CMM MUST set a time-to-live (TTL) for data keys in the
# CMC.  This value must be greater than zero.

[[spec]]
level = "MUST"
quote = '''
The Caching CMM MUST set a time-to-live (TTL) for data keys in the
CMC.
'''

