target = "compliance/framework/caching-cmm.txt#2.5.1"

# 2.5.1.  Underlying Cryptographic Materials Cache
#
# The caching CMM intercepts requests for encryption (cmm-
# interface.md#encryption-materials-request) and decryption (cmm-
# interface.md#decrypt-materials-request) materials and forwards them
# to the underlying cryptographic materials cache (CMC) (cryptographic-
# materials-cache.md).
# 
# Multiple caching CMMs MAY share the same cryptographic materials
# cache, but by default MUST NOT use each other's cache entries.  If
# multiple caching CMMs are attached to the same cryptograhic materials
# cache, they will share cache entries if and only if the partition ID
# (Section 2.5.4) parameter is set to the same string.

[[spec]]
level = "MUST"
quote = '''
Multiple caching CMMs MAY share the same cryptographic materials
cache, but by default MUST NOT use each other's cache entries.
'''

