target = "compliance/framework/caching-cmm.txt#2.7"

# 2.7.  Appendix A: Cache Entry Identifier Formulas
#
# When accessing the underlying CMC, the caching CMM MUST use the
# formulas specified in this appendix in order to compute the cache
# entry identifier (cryptographic-materials-cache.md#cache-identifier).

[[spec]]
level = "MUST"
quote = '''
When accessing the underlying CMC, the caching CMM MUST use the
formulas specified in this appendix in order to compute the cache
entry identifier (cryptographic-materials-cache.md#cache-identifier).
'''

