target = "compliance/framework/caching-cmm.txt#2.7.4"

# 2.7.4.  Decryption Materials
#
# When the caching CMM receives a Decrypt Materials request, it MUST
# calculate the cache entry identifier as the SHA-512 hash of the
# concatenation of the following byte strings, in the order listed:
# 
# 1.  The SHA-512 hash of a UTF-8 encoding of the caching CMM's
#     Partition ID
# 
# 2.  The two-byte algorithm suite ID corresponding to the algorithm
#     suite in the request
# 
# 3.  The concatenation of the lexicographically-sorted SHA-512 hashes
#     of the serialized encrypted data keys, where serialization is as
#     defined in the Encrypted Data Key Entries specification
#     (../../data-format/message-header.md#encrypted-data-key-entries).
# 
# 4.  A sentinel field of 512 zero bits (or equivalently, 64 null
#     bytes), indicating the end of the key hashes
# 
# 5.  The SHA-512 hash of the serialized encryption context
# 
# As a formula:
# 
# "EDK_HASHES = [SHA512(SerializeEncryptedDataKey(key)) for key in
# decryptMaterialsRequest.encryptedDataKeys] ENTRY_ID = SHA512(
# SHA512(UTF8Encode(cachingCMM.partitionId)) +
# AlgorithmSuiteId(decryptMaterialsRequest.algorithmSuite) +
# CONCATENATE(SORTED(EDK_HASHES)) + PADDING_OF_512_ZERO_BITS + SHA512(S
# erializeEncryptionContext(decryptMaterialsRequest.encryptionContext))
# )"

[[spec]]
level = "MUST"
quote = '''
When the caching CMM receives a Decrypt Materials request, it MUST
calculate the cache entry identifier as the SHA-512 hash of the
concatenation of the following byte strings, in the order listed:
'''

