target = "compliance/framework/caching-cmm.txt#2.7.3"

# 2.7.3.  Encryption Materials, With Algorithm Suite
#
# If the Get Encryption Materials request does specify an algorithm
# suite, then the cache entry identifier MUST be calculated as the
# SHA-512 hash of the concatenation of the following byte strings, in
# the order listed:
# 
# 1.  The SHA-512 hash of a UTF-8 encoding of the caching CMM's
#     Partition ID
# 
# 2.  One byte with value 1 ("0x01")
# 
# 3.  The two-byte algorithm suite ID corresponding to the algorithm
#     suite in the request
# 
# 4.  The SHA-512 hash of the serialized encryption context
# 
# As a formula:
# 
# "ENTRY_ID = SHA512( SHA512(UTF8Encode(cachingCMM.partitionId)) + 0x01
# + AlgorithmSuiteId(getEncryptionMaterialsRequest.algorithmSuite) + SH
# A512(SerializeEncryptionContext(getEncryptionMaterialsRequest.encrypt
# ionContext)) )"

[[spec]]
level = "MUST"
quote = '''
If the Get Encryption Materials request does specify an algorithm
suite, then the cache entry identifier MUST be calculated as the
SHA-512 hash of the concatenation of the following byte strings, in
the order listed:
'''

