target = "compliance/framework/caching-cmm.txt#2.7.2"

# 2.7.2.  Encryption Materials, Without Algorithm Suite
#
# If the Get Encryption Materials request does not specify an algorithm
# suite, then the cache entry identifier MUST be calculated as the
# SHA-512 hash of the concatenation of the following byte strings, in
# the order listed:
# 
# 1.  The SHA-512 hash of a UTF-8 encoding of the caching CMM's
#     Partition ID
# 
# 2.  One null byte ("0x00")
# 
# 3.  The SHA-512 hash of the serialized encryption context
# 
# As a formula:
# 
# "ENTRY_ID = SHA512( SHA512(UTF8Encode(cachingCMM.partitionId)) + 0x00
# + SHA512(SerializeEncryptionContext(getEncryptionMaterialsRequest.enc
# ryptionContext)) )"

[[spec]]
level = "MUST"
quote = '''
If the Get Encryption Materials request does not specify an algorithm
suite, then the cache entry identifier MUST be calculated as the
SHA-512 hash of the concatenation of the following byte strings, in
the order listed:
'''

