target = "compliance/client-apis/client.txt#2.4.2"

# 2.4.2.  Maximum Number Of Encrypted Data Keys
#
# A AWS Encryption SDK message can contain multiple encrypted data
# keys.  This is the maximum number of encrypted data keys that the
# client will attempt to unwrap.  Callers MUST have a way to disable
# this limit.

[[spec]]
level = "MUST"
quote = '''
Callers MUST have a way to disable
this limit.
'''

