target = "compliance/client-apis/client.txt#2.4.1"

# 2.4.1.  Commitment Policy
#
# Some algorithm suites provide a commitment that one and only one data
# key can be used to decrypt the plaintext.  Commitment policies
# control which algorithm suites are enabled for encrypt (encrypt.md)
# and decrypt (decrypt.md).  As well as which algorithm suite is the
# default.
# 
# The AWS Encryption SDK MUST provide the following commitment
# policies:
# 
# *  FORBID_ENCRYPT_ALLOW_DECRYPT
# 
# *  REQUIRE_ENCRYPT_ALLOW_DECRYPT
# 
# *  REQUIRE_ENCRYPT_REQUIRE_DECRYPT

[[spec]]
level = "MUST"
quote = '''
The AWS Encryption SDK MUST provide the following commitment
policies:
'''

