target = "compliance/client-apis/client.txt#2.4.2.1"

# 2.4.2.1.  FORBID_ENCRYPT_ALLOW_DECRYPT
#
# When the commitment policy "FORBID_ENCRYPT_ALLOW_DECRYPT" is
# configured:
# 
# *  "03 78" MUST be the default algorithm suite
# 
# *  encrypt (encrypt.md) MUST only support algorithm suites that have
#    a Key Commitment (../framework/algorithm-suites.md#algorithm-
#    suites-encryption-key-derivation-settings) value of False
# 
# *  decrypt (decrypt.md) MUST support all algorithm suites

[[spec]]
level = "MUST"
quote = '''
*  "03 78" MUST be the default algorithm suite
'''

[[spec]]
level = "MUST"
quote = '''
*  encrypt (encrypt.md) MUST only support algorithm suites that have
a Key Commitment (../framework/algorithm-suites.md#algorithm-
suites-encryption-key-derivation-settings) value of False
'''

[[spec]]
level = "MUST"
quote = '''
*  decrypt (decrypt.md) MUST support all algorithm suites
'''

