target = "compliance/client-apis/client.txt#2.5.1"

# 2.5.1.  Encrypt
#
# The AWS Encryption SDK Client MUST provide an encrypt
# (./encrypt.md#input) function that will honor the client's configured
# commitment policy (Section 2.4.1).

[[spec]]
level = "MUST"
quote = '''
The AWS Encryption SDK Client MUST provide an encrypt
(./encrypt.md#input) function that will honor the client's configured
commitment policy (Section 2.4.1).
'''

