target = "compliance/framework/aws-kms/aws-kms-mrk-aware-master-key-provider.txt#2.5"

# 2.5.  Interface
#
# MUST implement the Master Key Provider Interface (../master-key-
# provider-interface.md#interface)

[[spec]]
level = "MUST"
quote = '''
MUST implement the Master Key Provider Interface (../master-key-
provider-interface.md#interface)
'''

