target = "compliance/framework/aws-kms/aws-kms-mrk-aware-master-key-provider.txt#2.7"

# 2.7.  Get Master Key
#
# The input MUST be the same as the Master Key Provider Get Master Key
# (../master-key-provider-interface.md#get-master-key) interface.
# 
# The function MUST only provide master keys if the input provider id
# equals "aws-kms".  In strict mode, the requested AWS KMS key ARN MUST
# match a member of the configured key ids by using AWS KMS MRK Match
# for Decrypt (aws-kms-mrk-match-for-decrypt.md#implementation)
# otherwise this function MUST error.  In discovery mode, the requested
# AWS KMS key identifier MUST be a well formed AWS KMS ARN.  In
# discovery mode if a discovery filter is configured the requested AWS
# KMS key ARN's "partition" MUST match the discovery filter's
# "partition" and the AWS KMS key ARN's "account" MUST exist in the
# discovery filter's account id set.
# 
# If the requested AWS KMS key identifier is not a well formed ARN the
# AWS Region MUST be the configured default region this SHOULD be
# obtained from the AWS SDK.  Otherwise if the requested AWS KMS key
# identifier is identified as a multi-Region key (aws-kms-key-
# arn.md#identifying-an-aws-kms-multi-region-key), then AWS Region MUST
# be the region from the AWS KMS key ARN stored in the provider info
# from the encrypted data key.  Otherwise if the mode is discovery then
# the AWS Region MUST be the discovery MRK region.  Finally if the
# provider info is identified as a multi-Region key (aws-kms-key-
# arn.md#identifying-an-aws-kms-multi-region-key) the AWS Region MUST
# be the region from the AWS KMS key in the configured key ids matched
# to the requested AWS KMS key by using AWS KMS MRK Match for Decrypt
# (aws-kms-mrk-match-for-decrypt.md#implementation).  An AWS KMS client
# MUST be obtained by calling the regional client supplier with this
# AWS Region.
# 
# In strict mode a AWS KMS MRK Aware Master Key (aws-kms-mrk-aware-
# master-key.md) MUST be returned configured with
# 
# *  The AWS KMS obtained by calling the regional client supplier.
# 
# *  The AWS KMS key in the configured key ids matched to the requested
#    AWS KMS key by using AWS KMS MRK Match for Decrypt (aws-kms-mrk-
#    match-for-decrypt.md#implementation).
# 
# *  The configured grant tokens.
# 
# In discovery mode a AWS KMS MRK Aware Master Key (aws-kms-mrk-aware-
# master-key.md) MUST be returned configured with
# 
# *  The AWS KMS obtained by calling the regional client supplier.
# 
# *  An AWS KMS key ARN where the "region" element is the AWS Region,
#    and every other ARN element matches the requested AWS KMS key ARN.
# 
# *  The configured grant tokens.
# 
# The output MUST be the same as the Master Key Provider Get Master Key
# (../master-key-provider-interface.md#get-master-key) interface.

[[spec]]
level = "MUST"
quote = '''
The input MUST be the same as the Master Key Provider Get Master Key
(../master-key-provider-interface.md#get-master-key) interface.
'''

[[spec]]
level = "MUST"
quote = '''
The function MUST only provide master keys if the input provider id
equals "aws-kms".
'''

[[spec]]
level = "MUST"
quote = '''
In strict mode, the requested AWS KMS key ARN MUST
match a member of the configured key ids by using AWS KMS MRK Match
for Decrypt (aws-kms-mrk-match-for-decrypt.md#implementation)
otherwise this function MUST error.
'''

[[spec]]
level = "MUST"
quote = '''
In strict mode, the requested AWS KMS key ARN MUST
match a member of the configured key ids by using AWS KMS MRK Match
for Decrypt (aws-kms-mrk-match-for-decrypt.md#implementation)
otherwise this function MUST error.
'''

[[spec]]
level = "MUST"
quote = '''
In discovery mode, the requested
AWS KMS key identifier MUST be a well formed AWS KMS ARN.
'''

[[spec]]
level = "MUST"
quote = '''
In
discovery mode if a discovery filter is configured the requested AWS
KMS key ARN's "partition" MUST match the discovery filter's
"partition" and the AWS KMS key ARN's "account" MUST exist in the
discovery filter's account id set.
'''

[[spec]]
level = "MUST"
quote = '''
In
discovery mode if a discovery filter is configured the requested AWS
KMS key ARN's "partition" MUST match the discovery filter's
"partition" and the AWS KMS key ARN's "account" MUST exist in the
discovery filter's account id set.
'''

[[spec]]
level = "MUST"
quote = '''
If the requested AWS KMS key identifier is not a well formed ARN the
AWS Region MUST be the configured default region this SHOULD be
obtained from the AWS SDK.
'''

[[spec]]
level = "MUST"
quote = '''
Otherwise if the requested AWS KMS key
identifier is identified as a multi-Region key (aws-kms-key-
arn.md#identifying-an-aws-kms-multi-region-key), then AWS Region MUST
be the region from the AWS KMS key ARN stored in the provider info
from the encrypted data key.
'''

[[spec]]
level = "MUST"
quote = '''
Otherwise if the mode is discovery then
the AWS Region MUST be the discovery MRK region.
'''

[[spec]]
level = "MUST"
quote = '''
Finally if the
provider info is identified as a multi-Region key (aws-kms-key-
arn.md#identifying-an-aws-kms-multi-region-key) the AWS Region MUST
be the region from the AWS KMS key in the configured key ids matched
to the requested AWS KMS key by using AWS KMS MRK Match for Decrypt
(aws-kms-mrk-match-for-decrypt.md#implementation).
'''

[[spec]]
level = "MUST"
quote = '''
An AWS KMS client
MUST be obtained by calling the regional client supplier with this
AWS Region.
'''

[[spec]]
level = "MUST"
quote = '''
In strict mode a AWS KMS MRK Aware Master Key (aws-kms-mrk-aware-
master-key.md) MUST be returned configured with
'''

[[spec]]
level = "MUST"
quote = '''
In discovery mode a AWS KMS MRK Aware Master Key (aws-kms-mrk-aware-
master-key.md) MUST be returned configured with
'''

[[spec]]
level = "MUST"
quote = '''
The output MUST be the same as the Master Key Provider Get Master Key
(../master-key-provider-interface.md#get-master-key) interface.
'''

