target = "compliance/framework/aws-kms/aws-kms-mrk-aware-master-key-provider.txt#2.8"

# 2.8.  Get Master Keys For Encryption
#
# The input MUST be the same as the Master Key Provider Get Master Keys
# For Encryption (../master-key-provider-interface.md#get-master-keys-
# for-encryption) interface.
# 
# If the configured mode is discovery the function MUST return an empty
# list.  If the configured mode is strict this function MUST return a
# list of master keys obtained by calling Get Master Key (aws-kms-mrk-
# aware-master-key-provider.md#get-master-key) for each AWS KMS key
# identifier in the configured key ids
# 
# The output MUST be the same as the Master Key Provider Get Master
# Keys For Encryption (../master-key-provider-interface.md#get-master-
# keys-for-encryption) interface.

[[spec]]
level = "MUST"
quote = '''
The input MUST be the same as the Master Key Provider Get Master Keys
For Encryption (../master-key-provider-interface.md#get-master-keys-
for-encryption) interface.
'''

[[spec]]
level = "MUST"
quote = '''
If the configured mode is discovery the function MUST return an empty
list.
'''

[[spec]]
level = "MUST"
quote = '''
If the configured mode is strict this function MUST return a
list of master keys obtained by calling Get Master Key (aws-kms-mrk-
aware-master-key-provider.md#get-master-key) for each AWS KMS key
identifier in the configured key ids
'''

[[spec]]
level = "MUST"
quote = '''
The output MUST be the same as the Master Key Provider Get Master
Keys For Encryption (../master-key-provider-interface.md#get-master-
keys-for-encryption) interface.
'''

